# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import webTransferApi_pb2 as webTransferApi__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc_tests package installed is at version {GRPC_VERSION},'
        + f' but the generated code in webTransferApi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc_tests module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebTransferApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc_tests.Channel.
        """
        self.makeWebTransfer = channel.unary_unary(
                '/web_transfer_api.WebTransferApi/makeWebTransfer',
                request_serializer=webTransferApi__pb2.IncomingWebTransfer.SerializeToString,
                response_deserializer=webTransferApi__pb2.OutgoingWebTransfer.FromString,
                _registered_method=True)


class WebTransferApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makeWebTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebTransferApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makeWebTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.makeWebTransfer,
                    request_deserializer=webTransferApi__pb2.IncomingWebTransfer.FromString,
                    response_serializer=webTransferApi__pb2.OutgoingWebTransfer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'web_transfer_api.WebTransferApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('web_transfer_api.WebTransferApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebTransferApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makeWebTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/web_transfer_api.WebTransferApi/makeWebTransfer',
            webTransferApi__pb2.IncomingWebTransfer.SerializeToString,
            webTransferApi__pb2.OutgoingWebTransfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
