operations = [
    {
        "refid": "daniyarRefIdSariev1234",
        "sessionkey": "1iJoU2nsFChCY3IhGsEw9A",
        "accountIdDebit": 2820,
        "accountCreditPropValue": '255',
        "accountCreditPropType": 'ACCOUNT_NO',
        "paymentPurpose": 'Payment for services',
        "amountDebit": '100',
        "qrPayment": True,
        "qrAccountChangeable": False,
        "qrComment": 'Payment for services',
        "qrServiceName": 'KICB',
        "qrServiceId": '04',
        "clientType": '1',
        "qrVersion": '01',
        "qrType": 'STATIC',
        "qrMerchantProviderId": 'p2p.kicb.net',
        "qrMerchantId": None,
        "qrAccount": '255',
        "qrMcc": '9999',
        "qrCcy": '417',
        "qrTransactionId": 'Test 1',
        "qrControlSum": 'c560'
    },
    {
        "refid": "johnDoeRefId1234",
        "sessionkey": "1iJoU2nsFChCY3IhGsEw9A",
        "accountIdDebit": 2820,
        "accountCreditPropValue": '255',
        "accountCreditPropType": 'ACCOUNT_NO',
        "paymentPurpose": 'Payment for products',
        "amountDebit": '10',
        "qrPayment": True,
        "qrAccountChangeable": False,
        "qrComment": 'Payment for products',
        "qrServiceName": 'KICB',
        "qrServiceId": '04',
        "clientType": '1',
        "qrVersion": '01',
        "qrType": 'STATIC',
        "qrMerchantProviderId": 'corp.kicb.net',
        "qrMerchantId": None,
        "qrAccount": '255',
        "qrMcc": '9999',
        "qrCcy": '417',
        "qrTransactionId": 'Test 2',
        "qrControlSum": '8cec'
    }
]

