export default {
  AUTH_GREETINGS: "Welcome to Internet Banking (I-Bank)",
  AUTH_LOGIN: "Login",
  AUTH_PASSWORD: "Password",
  AUTH_BUTTON: "Sign in",
  AUTH_PASWORDRESET: "Forgot password?",
  AUTH_REGISTRATION: "Register",
  AUTH_DISCLAIMER: `Attention! If you are using someone else's computer, it is strongly recommended to turn on the private browsing mode in your browser. In the lower right corner or in the address bar of your browser you should see the icon for a secure connection as a closed lock 🔒. To verify the data owner of the site click on the icon. For more information see "Security". Bank will never request confirmation of password and login by means of emails. If you receive suspicious messages requesting your personal data: login and password ignore such messages and do not enter your data. Please inform us by the following email ibank@kicb.net or leave message at Call centre: +996 (312) 620 101.`,
  AUTH_CALLCENTRE: "24/7 Call-centre",
  AUTH_COPYRIGHTFOOTER: "2022, Kyrgyz Investement and Credit Bank (KICB). All rights reserved. Licensed by NBKR # 046.",
  LOGIN_GREETINGS: "Login to Internet banking",
  LOGIN_CODEHASBEENSENT: "Code was sent to your phone number",
  LOGIN_RETRYSMS: "Resend SMS in",
  LOGIN_EMAIL: "Receive confirmation code via email",
  LOGIN_BUTTON: "Confirm",
  MAINPAGE_NATURALPERSON: "Individual",
  MAINPAGE_ENTITYPERSON: "Legal Entity",
  NO_TRANSACTION: 'No transaction',
  MAINPAGE_ACCOUNTS: "Accounts",
  MAINPAGE_PAYMENTS: "Payments",
  MAINPAGE_HISTORY: "History",
  MAINPAGE_SHOWCASE: "Store",
  MAINPAGE_MESSAGES: "Messages",
  MAINPAGE_PROFILE: "Profile",
  MAINPAGE_ARCHIVE: "Archive",
  MAINPAGE_CARDS: "Card accounts",
  MAINPAGE_ACCOUNTTYPE: "Account type",
  MAINPAGE_BALANCE: "Balance",
  MAINPAGE_DETAILS: "Account details",
  MAINPAGE_BANKSTATEMENT: "Account Statement",
  MAINPAGE_OPENACCOUNT: "You don't have any accounts",
  MAINPAGE_OPENCARD: "Open card",
  MAINPAGE_DEPOSITS: "Deposits",
  MAINPAGE_DEPOSIT: "Deposit",
  MAINPAGE_OPENDEPOSIT: "Open deposit",
  MAINPAGE_DEPOSITNAME: "Deposit name",
  MAINPAGE_ACCRUED: "Accrued interest",
  MAINPAGE_REPLENISH: "Replenish",
  MAINPAGE_LOAN: "Loans",
  TYPE_LOAN: 'Loan type',
  TYPE_DEPOSIT: 'Type of deposit/Contract',
  // CONTRACT : 'Контракт',
  MAINPAGE_GETLOAN: "Get loan",
  MAINPAGE_GETLOANDETAILS: "Get loan",
  MAINPAGE_LOANNAME: "Loan name",
  MAINPAGE_LOANSUM: "Amount",
  MAINPAGE_LOANREPAYMENT: "Loan repayment",
  MAINPAGE_LOANLEFTOVER: "Balance",
  MAINPAGE_LOANSCHEDULE: "Schedule",
  MAINPAGE_LOANINTERESTRATE: "interest rate",
  MAINPAGE_EXCHANGERATE: "Exchange rates",
  MAINPAGE_NOCASH: "Non-cash rates",
  MAINPAGE_CASH: "Cash rates",
  MAINPAGE_CURRENCY: "Currency",
  MAINPAGE_BUYCURRENCY: "Buy",
  MAINPAGE_SELLCURRENCY: "Sale",
  MAINPAGE_NBKR: "NBKR",
  MAINPAGE_CROSSEXCHANGERATE: "Сross-rates to USD",
  MAINPAGE_GOTOEXCHANGE: "Go to exchange",
  MAINPAGE_ELSOM: "Elsom",
  MAINPAGE_RECENTACTIVITES: "Recent events",
  MAINPAGE_ENDOFPOWEROFATTORNEY: "End of power of attorney",
  MAINPAGE_PASSPORTEXPIRATIONDATE: "End of expiration date of passport",
  MAINPAGE_SEEALLACTIVITIES: "View all events",
  MAINPAGE_MAP: "Offices and ATMs",
  MAINPAGE_ACTIVITYTIME: "Payment at 08:40",
  MAINPAGE_TEMPLATE: "Favorites",
  MAINPAGE_TABLECOLUMN_TYPE: "Account type",
  MAINPAGE_HEADER_TITLE: "Favorites",
  MAINPAGE_TABLECOLUMN_BALANCE: "Balance",
  MAINPAGE_TABLECOLUMN_REQUISITES: "Account details",
  MAINPAGE_TABLECOLUMN_CHECKOUT: "Account Statement",
  MAINPAGE_SECTION_ARCHIVE: "Archive",
  MAINPAGE_TABLECOLUMN_TYPEOFCARD: "Card type",
  MAINPAGE_TABLECOLUMN_TYPEOFWALLET: "E-wallet type",
  MAINPAGE_WALLET_TITLE: "Electronic wallets",
  MAINPAGE_WALLET_JOIN: "Add ELSOM",
  MAINPAGE_WALLET_SUBTEXT: 'Receive access to Elsom from "KICB"',
  MAINPAGE_DEPOSITS_NAME: "Depostit name",
  MAINPAGE_DEPOSITS_SUM: "Amount",
  MAINPAGE_DEPOSITS_PERCENT: "Accrued interest",
  MAINPAGE_DEPOSITS_ADD: "Replenish",
  MAINPAGE_DEPOSITS_RATE: "Interest rate",
  MAINPAGE_CARD_ACTION: "Open card",
  MAINPAGE_CREDITS_ACTION: "Get loan",
  MAINPAGE_CREDITS_TITLE: "Loans",
  MAINPAGE_CREDITS_NAME: "Loan name",
  MAINPAGE_CREDITS_REPAYMENT: "Loan repayment",
  MAINPAGE_CREDITS_REMAINDER: "Balance",
  MAINPAGE_CREDITS_GRAPH: "Schedule",
  MAINPAGE_RECENTEVENTS_ITEM: "Amount to pay",
  MAINPAGE_WALLET_MODAL_TITLE: "Add Elsom wallet",
  MAINPAGE_WALLET_MODAL_BILL: "Electronic wallet number",
  PAYMENTS_TRANSFER: "Transfers",
  TOP_UP_ACCOUNT: "Top up your account",
  REPLENISHMENT_FROM_VISA: "Replenishment from VISA card",
  REPLENISHMENT_FROM_VISA_OTHER_BANK: "Replenishment from VISA card of another bank",
  ELCARD: "Elcard",
  TRANSFER_TO_VISA: "Transfers to VISA cards of other banks",
  PAYMENTS_MYACCOUNTS: "Between own accounts",
  CARD_VISA_CARD_OCT: "Transfer to Visa card",
  SALYK_PAYMENT: "Payment of immovable estate tax",
  PAYMENTS_KICBACCOUNTS: "To KICB customers",
  PAYMENTS_OTHERBANKS: "To other banks within KR in KGS",
  TITLE_CLEARING: 'Clearing',
  TITLE_GROSS: 'Clearing',
  PAYMENTS_SWIFT: "Abroad - SWIFT",
  ALL_PAYMENTS: 'All',
  PAYMENTS_EXCHANGECURRENCY: "Currency exchange",
  PAYMENTS_CARD_OTHER_BANK: "Transfer to the card of other Bank",
  PAYMENTS_PAYMENTS: "Payments",
  PAYMENTS_MOBILE: "Mobile top-up",
  PAYMENTS_TAXES: "Tax payments",
  PAYMENTS_FINES: "Penalties",
  PAYMENTS_GOVERNMENT: "Government services",
  PAYMENTS_INTERNET: "Internet",
  PAYMENTS_TV: "Television",
  PAYMENTS_INSURANCE: "Insurance",
  PAYMENTS_UTILITY: "Utilities",
  PAYMENTS_ED: "Education",
  PAYMENTS_FINANCE: "Financial services",
  PAYMENTS_RENT: "Rent",
  PAYMENTS_WALLETS: "Electronic wallets",
  PAYMENTS_FUN: "Entertainment",
  PAYMENTS_CHARITY: "Charity",
  PAYMENTS_MMM: "Network business",
  PAYMENTS_TAXI: "Taxi",
  PAYMENTS_ADS: "Advertisement",
  PAYMENTS_OTHER: "Others",
  PAYMENTS_SEARCH: "Enter the name or category of the service",
  PAYMENTS_TEMPLATES: "Template of transfer between own accounts ",
  PAYMENTS_TRANSFERS: "Transfer between own accounts ",
  PAYMENTS_NOTEMPLATES: "There are no templates yet",
  PAYMENTSGENERIC_REQUISITES: "Account details",
  PAYMENTSGENERIC_ACCOUNTCREDIT: "From account",
  PAYMENTSGENERIC_ACCOUNTDEBIT: "To account",
  PAYMENTSGENERIC_CHOOSEACCOUNT: "Choose account",
  PAYMENTSGENERIC_SUMOFTRANSFER: "Transfer amount",
  PAYMENTSGENERIC_CONFIRMTRANSFER: "Confirm transfer",
  PAYMENTSGENERIC_STATUSOFOPERATION: "Operation status",
  PAYMENTSGENERIC_PERSONALACCOUNT: "Personal account",
  PAYMENTSGENERIC_CHOOSESERVICE: "Select service",
  PAYMENTSGENERIC_REQUISITESFILL: "Fill up details",
  PAYMENTSGENERIC_CATEGORYSELECTION: "Category selection",
  PAYMENTSGENERIC_TAXCALCULATION: "Tax calculation",
  PAYMENTSGENERIC_SUMOFREPLENISH: "Amount to be credited",
  PAYMENTSGENERIC_CONFIRMPAYMENT: "Confirmation",
  ACCOUNTDETAILS_SUMINBLOCK: "Amount in block",
  ACCOUNTDETAILSREQUISITES_CLIENT: "Client",
  ACCOUNTDETAILSREQUISITES_BANKMEDIATOR: "Intermediary bank",
  ACCOUNTDETAILS_RENAME: "Rename account",
  ACCOUNTDETAILS_RENAMEOLD: "Current account name",
  ACCOUNTDETAILS_RENAMENEW: "New name",
  ACCOUNTDETAILS_RENAMESAVED: "Save",
  ACCOUNTDETAILS_BANKSTATEMENT: "Account Statement",
  ACCOUNTDETAILS_REQUISITES: "Account details",
  ACCOUNTDETAILS_PAYANDTRANSFER: "Pay",
  ACCOUNTDETAILS_REPLENISH: "Own account replenishment",
  ACCOUNTDETAILSSTATEMENT_CLIENT: "Client",
  ACCOUNTDETAILSSTATEMENT_CURRENCY: "Account currency",
  ACCOUNTDETAILSSTATEMENT_BALANCE: "Actual balance",
  ACCOUNTDETAILSSTATEMENT_STAMENENTCREATION: "Get statement",
  ACCOUNTDETAILSSTATEMENT_DOWNLOAD: "Download",
  ACCOUNTDETAILSSTATEMENT_PRINT: "Print",
  ACCOUNTDETAILSSTATEMENT_DATE: "Date",
  ACCOUNTDETAILSSTATEMENT_CONTREAGENT: "Counterparty",
  ACCOUNTDETAILSSTATEMENT_SUMMART: "Description",
  ACCOUNTDETAILSSTATEMENT_SUM: "Amount",
  ACCOUNTDETAILSSTATEMENT_LEFTOVER: "Balance",
  ACCOUNTDETAILSSTATEMENT_TEXT: "Please check this account statement and inform us of any discrepancy within 14 days.",
  CARD_DETAILS_TITLE: 'Debit card',
  CARDDETAILS_LEFTOVER: "Irreducible balance",
  CARDDETAILS_BYDEFAULT: "Default card",
  CARDDETAILS_NFCPAY: "NFC payments",
  CARDDETAILS_CARDBLOCK: "Card blocking",
  CARDDETAILS_INTERNETPAY: "Internet payments",
  CARDDETAILS_SMS: "SMS notifications",
  HEADER_NOTIFICATIONS: "Notifications",
  CARDDETAILS_RERELEASE: "Card reissue",
  CARDDETAILS_PINCODE: "Set PIN",
  CARDDETAILS_LIMIT: "Limits management",
  CARDDETAILS_SETTINGS: "Settings",
  CARDDETAILS_REQUISITESCARD: "Card details",
  CARDDETAILS_MINISTATEMENT: "Mini statement",
  CARDDETAILS_STATEMENTPERIOD: "Statement for period",
  CARDDETAILS_OVERDRAFT: "Request overdraft",
  CARDDETAILS_PAYANDTRANSFER: "Pay and transfer",
  CARDDETAILS_REPLENISH: "Own card replenishment",
  CARDDETAILSMINISTATEMENT_PLACEDATE: "Location/Date",
  CARDDETAILSMINISTATEMENT_SUMINCURRENCYACCOUNT: "Amount in charge currency",
  CARDDETAILSMINISTATEMENT_SUMINCURRENCY: "Amount in bill currency",
  CARDDETAILSMINISTATEMENT_CARDTYPE: "Card type",
  CARDDETAILSMINISTATEMENT_AVAILABLEBALANCE: "Available balance",
  CARDDETAILSMINISTATEMENT_PRINT: "Print",
  DEPOSITDETAILS_PERCENTNOW: "%% at this moment",
  DEPOSITDETAILS_PERCENTLATER: "%% to payment at the end of the term",
  DEPOSITDETAILS_OPENDATE: "Opening date",
  DEPOSITDETAILS_CLOSEDATE: "Closing date",
  DEPOSITDETAILS_INTERESTRATE: "Interest rate",
  DEPOSITDETAILS_NAME: "Deposit name",
  DEPOSITDETAILS_SUMOFREPLENISH: "Replenishment amount",
  DEPOSITDETAILS_ACCOUNTUSED: "From account",
  DEPOSITDETAILS_REPLENISH: "Replenish",
  DEPOSITDETAILS_RENAME: "Rename deposit",
  DEPOSITDETAILS_CURRENTNAME: "Current name of the deposit",
  DEPOSITDETAILS_NEWNAME: "New name",
  LOANDETAILS_REPLENISHLOAN: "Replenish loan account",
  LOANDETAILS_REQUISITESLOAN: "Loan account details",
  LOANDETAILS_SCHEDULE: "Repayment schedule",
  LOANDETAILS_SUMOFLOAN: "Loan amount",
  LOANDETAILS_LEFTOVEROFMAINSUM: "Balance of principal amount",
  LOANDETAILS_INTERESTRATE: "Interest rate",
  LOANDETAILS_LOAN: "Loans",
  LOANDETAILS_ACTIONSLOAN: "Actions on the loan",
  LOANDETAILS_NEXTPAYMENT: "Next payment: ",
  SHOWCASE_REQUISITIONING: "Submission of applications",
  SHOWCASE_GETLOAN: "Get loan",
  SHOWCASE_GETLOANDETAILS: "Easy loans starting from 13%",
  SHOWCASE_OPENDEPOSITDETAILS: "Start savings today",
  SHOWCASE_GETLOANBUTTON: "Apply",
  SHOWCASE_OPENDEPOSITBUTTON: "Open",
  SHOWCASE_CARDSWALLETS: "Cards and wallets",
  SHOWCASE_WALLETS: "Wallets",
  SHOWCASE_ACQUIRING: "Connect acquiring",
  SHOWCASE_OPENVIRTUALCARD: "Open virtual card",
  SHOWCASE_OPENDEBET: "Open debit card",
  SHOWCASE_BANKPRODUCTS: "Bank products",
  SHOWCASE_CHECKBOOK: "Order check book",
  SHOWCASE_OBLIGATIONS: "Buy bonds",
  SHOWCASE_CERTIFICATE: "Get accounts certificate",
  SHOWCASE_SAFECELL: "Book safe deposit box",
  SETTINGS_FIOISNEWFULLNAME: "Full name",
  SETTINGS_PASSPORTID: "Passport number",
  SETTINGS_EXPIRYDATE: "Expiration date",
  SETTINGS_PROPISKA: "Registration address",
  SETTINGS_FACTUAL: "Actual address",
  SETTINGS_PHONENUMBER: "Phone number",
  SETTINGS_SETTINGSCEPTION: "Settings",
  SETTINGS_LIMITS: "Limits",
  SETTINGS_COMPANY: "Company Settings",
  COMPANY: 'Company',
  USER: 'Users',
  NO_EVENTS: 'No events',
  PAYMENT_TYPE_CORP_TRANSACTIONS: 'Payment type',
  DATE_CREATION_TABLE: 'Date of creation',
  APPOPINTMENT: 'Appointments',
  STATUS_SENT: 'Status / Sent',
  CREACTED_SIGNED: 'Created/ Signed',
  DOCUMENT_DATE: 'Document No / Date',
  FORM_OPERATION: 'To account/ Operation type',
  NO_ACTIVE_CARD: 'No active cards',
  NO_DEPOSITS: 'No deposits',
  NO_LOAN: 'No Loans',
  SETTINGS_TARIFFS: "Tariffs",
  SETTINGS_CALENDAR: "Calendar",
  SETTINGS_SCHEDULEDPAY: "Scheduled payments",
  SETTINGS_TEMPLATEs: "Templates",
  SETTINGS_TEMPLATEs_ACCOUNTDEBIT: "To account",
  SETTINGS_TEMPLATEs_ACCOUNTCREDIT: "Payment details",
  SETTINGS_TEMPLATEs_PURPOSE: "Amount to be credited",
  SETTINGS_TEMPLATEs_REDO: "Execute",
  SETTINGS_TEMPLATEs_CHANGENAME: "Rename template",
  SETTINGS_TEMPLATEs_SHEDULE: "Set schedule",
  SETTINGS_TEMPLATEs_DELETE: "Delete",
  SETTINGS_TEMPLATEs_CHANGINGNAME: "Rename template",
  SETTINGS_TEMPLATEs_EDIT: "Edit",
  SETTINGS_TEMPLATEs_CANCEL: "Cancel",
  SETTINGS_TEMPLATEs_REPEAT: "Repeat",
  SETTINGS_TEMPLATEs_INDEFINITELY: "Indefinitely",
  SETTINGS_TEMPLATEs_PERIOD: "Periodicity",
  SETTINGS_TEMPLATEs_ONCEAWEEK: "Once a week",
  SETTINGS_TEMPLATEs_FORNIGHTLY: "Every 2 weeks",
  SETTINGS_TEMPLATEs_FORMONTHLY: "Once a month",
  SETTINGS_TEMPLATEs_FORDATE: "On the appointed dates",
  SETTINGS_TEMPLATEs_SETPERIOD: "Select period",
  SETTINGS_TEMPLATEs_DAYOFTHEWEEK: "Day of the week",
  SETTINGS_HISTORYVHODA: "Login history",
  SETTINGS_LANGUAGECHANGE: "Select language",
  SETTINGS_ABOUTSITE: "About site",
  SETTINGS_EXIT: "Logout",
  SETTINGS_PROFILE_CHANGE: "Change of authentication type",
  SETTINGS_PROFILE_REPLACE: "",
  SETTINGS_PROFILE_CHANGE_PASSWORD: "Transaction history",
  SETTINGS_PROFILE_CHANGE_LOGIN: "Purpose of payment",
  SETTINGS_PROFILE_GET_CODE: "Receive Google Authenticator initialization code",
  SETTINGS_QUESTION_TITLE: "Change security question",
  SETTINGS_QUESTION_DESC: "Please select a security question for further possibility of recover forgotten password",
  SETTINGS_QUESTION_CHOOSE: "Choose security question",
  SETTINGS_QUESTION_ANSWER: "Your response",
  SETTINGS_PASSWORD_NOW: "Current password",
  SETTINGS_PASSWORD_NEW: "New password",
  SETTINGS_PASSWORD_NEW_CONFIRM: "Repeat of new password",
  SETTINGS_LOGIN_NOW: "Current login",
  SETTINGS_LOGIN_NEW: "New login",
  SETTINGS_LOGIN_NEW_CONFIRM: "Repeat of new login",
  HISTORY_ACCEPT: "Accepted",
  HISTORY_NOACCEPT: "Not accepted",
  HISTORY_DEPOSIT: "Deposit replenishment",
  HISTORY_DEPOSIT_OPEN: "Open deposit",
  BILL_NAME: "Account",
  BILL_SETTINGS: "Settings",
  BILL_TITLE: "Current account",
  TRANSFER_TITLE: "Currency exchange",
  TRANSFER_NAV_FIRST: "Payments and transfers",
  TRANSFER_TO_CARDS_OTHER_BANKS: "Transfer to the card of other Bank",
  TRANSFER_NAV_SECOND: "Currency exchange",
  TRANSFER_NAVBAR_REQ: "Account details",
  TRANSFER_NAVBAR_CONFIRM: "Confirm transfer",
  TRANSFER_NAVBAR_STATUS: "Operation status",
  TRANSFER_NAVBAR_PAYMENT: "Payment",
  TRANSFER_BILL_IN: "To account",
  TRANSFER_BILL_OUT: "From account",
  TRANSFER_DIRECTION_COUNTRY: "Country",
  TRANSFER_SELECT_CITY: "City",
  TRANSFER_DIRECTION_CITY: "Direction-city",
  TRANSFER_DIRECTION_FULL_NAME_RECIPIENT: "Recipient's full name",
  TRANSFER_DIRECTION_FULL_NAME_RECIPIENT_PASSPORT: "Recipient's full name according to passport",
  TRANSFER_EXCHANGE: "Exchange rate",
  TRANSFER_SUM_IN: "Amount to be credited",
  TRANSFER_SUM_OUT: "Amount to be debited",
  TRANSFER_BTN_TEXT: "Exchange",
  TRANSFER_TEMPLATE: "Template of transfer between own accounts ",
  TRANSFER_TEMPLATE_ELCART: "Template of transfers to Elcard",
  TRANSFER_TEMPLATE_VISA: "Template of transfers to Visa",
  TRANSFER_AMOUNT_IN: 'Amount to be credited ',
  TRANSFER_AMOUNT_OUT: 'Amount to be debited',
  TRANSFER_EXCHANGE_RATE: 'Rate',
  SERVICE_POINTS_FILTER: "Filter",
  HEADER_CALLCENTER: "Call-centre",
  PAYMENT_TITLE: "Favorites",
  PAYMENT_PLACEHOLDER: "Enter the name or category of the service",
  HISTORY_TITLE: "Transaction history",
  HISTORY_INPUT_USERNAME: "Purpose of payment",
  HISTORY_INPUT_DATE: "Choose date",
  HISTORY_INPUT_ACCESS: "Accepted",
  HISTORY_INPUT_NOT_ACCESS: "Not accepted",
  HISTORY_INPUT_TODAY: "Today",
  MESSAGES_TITLE: "Messages",
  MESSAGES_BTN: "Write a message",
  "MESSAGES_CHOSE-THEME": "Select the subject of your appeal:",
  "FOOTER_CALL-CENTER": "24/7 Call centre",
  WALLETS_DATE_AND_TIME: "Date and time",
  WALLETS_COUNTERAGENT: "Counterparty",
  WALLETS_DESCRIPTION: "Description",
  WALLETS_SUM: "Amount",
  WALLETS_LAST_TRANSACTIONS: "Last transactions",
  WALLETS_ADD_BILL: "Replenish",
  WALLETS_ADD_BILL_CHOOSE: "Choose the acount",
  WALLETS_ADD_BILL_SUBMIT: "Confirm",
  WALLETS_ADD_BILL_SCHET: "From account",
  WALLETS_MODAL_INFO: 'Attention! Wallet data will not be displayed. Continue?',
  WALLETS_MODAL_YES: 'Yes',
  WALLETS_MODAL_CANCEL: 'Cancel',
  WALLETS_UNTIE_THE_WALLET: 'Unlink e-wallet',
  WALLETS_SUCCESSFULLY: 'ELSOM successfully linked',
  WALLETS_CONFIRM_OTP: 'Confirmation',
  WALLETS_UNTIED: ({named}) =>  `Elsom ${named('phoneNumber')} successfully unlinked`,
  CREDIT_GET_TITLE: "Loan application",
  CREDIT_GET_STATUS: "Application status",
  CREDIT_GET_TYPE_OF_CREDIT_LABEL: "Loan type",
  CREDIT_GET_TYPE_OF_CREDIT_INPUT: "Select loan type",
  CREDIT_GET_PHONE: "Phone number",
  CREDIT_GET_DOCS: "Supplementary documents",
  "PAYMENTS_TRANSFERS_SCHET_LABEL-IN": "From account",
  "PAYMENTS_TRANSFERS_SCHET_INPUT-IN": "Choose account",
  "PAYMENTS_TRANSFERS_SCHET_LABEL-OUT": "To account",
  "PAYMENTS_TRANSFERS_SCHET_INPUT-OUT": "Choose account",
  PAYMENTS_TRANSFERS_SUM: "Transfer amount",
  PAYMENTS_TRANSFERS_CCY: "Transfer currency",
  PAYMENTS_TRANSFERS_BTN: "Transfer ",
  PAYMENTS_TRANSFERS_TO_OTHER_SCHET: "Account",
  PAYMENTS_TRANSFERS_TO_OTHER_CARD: "Card",
  PAYMENTS_TRANSFERS_TO_OTHER_PHONE: "Phone number",
  TELEPHONE: 'Telephone',
  "PAYMENTS_TRANSFERS_TO_OTHER_SCHET-NUMBER": "Recipient's account",
  "PAYMENTS_TRANSFERS_TO_OTHER_CARD-NUMBER": "Recipient's card number",
  "PAYMENTS_TRANSFERS_TO_OTHER_PHONE-NUMBER": "Recipient's phone number",
  "PAYMENTS_TRANSFERS_TO_OTHER_CARD-RECIPIENT_NAME": "Recipient's first and last name",
  "PAYMENTS_TRANSFERS_TO_VISA_CARD-NUMBER": "Replenishment card number",
  "PAYMENTS_TRANSFERS_TO_OTHER_CARD_DEBIT-NUMBER": "Debit card number",
  PAYMENTS_TRANSFERS_TO_OTHER_TEMPLATES: "Template of transfer to KICB customer",
  PAYMENTS_TRANSFERS_TO_OTHER: "Transfer to KICB customer’s account",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_TITLE: "Payments to other banks within KR in KGS (Clearing&Gross)",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_SOURCE: "From account",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_FAST_PAYMENT: "Urgent payment/Gross",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_DATE: "Transfer Date",
  PAYMENTS_BATCH_LOADING: "Importing documents",
  SALARY: "Salary",
  PAYMENTS_MONEY_SYSTEM: "Money transfer systems",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_NAME: "Recipient's name",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_BIK: "BIC of the recipient's bank",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_NAZNACHENIE: "Purpose",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_CODE: "Payment code by classifier",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_THEN: "Amount",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_TEMPLATES: "Template of transfer to other banks in KGS (clearing/gross)",
  PAYMENTS_TRANSFERS_SWIFT_TEMPLATES: "Template of SWIFT transfers",
  PAYMENTS_TRANSFERS_SWIFT_TITLE: "Foreign currency transfers",
  PAYMENTS_TRANSFERS_SWIFT_VALUTA: "Payment currency",
  PAYMENTS_TRANSFERS_SWIFT_DATE: "Value date",
  PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER: "Beneficiary’s bank",
  ELECTRIC_CAR: "Electric car",
  BANK: "Bank",
  RELATION_WITH_BANK: "Relation with Bank",
  PURPOSE_OF_OPENING: "Purpose of e-wallet opening",
  MONTHLY_TURNOVER: "Monthly turnover",
  SWIFT_TEXT_DETAILS: '     Hereby we certify that information presented in this application is complete and correct. The Client is informed and agree with commission of correspondent bank $50 for amendments/ inquires/ addition information on payment instruction.  Bank is not liable for errors or delays in transmission caused by neglect or default acts or beyond Bank\'s control.The Bank shall execute instructions and orders according to the rrent legislation of Kyrgyz Republic. \n' +
    '     We also confirm that the Bank informed about possible risks of non-execution, blocking transfers and debiting commission from the principal amount of the payment from Intermediary Banks to Russian Federation, as well as about the possible imposition of new sanctions against banks of the Russian Federation. The Bank is not responsible for the execution of transfers to Russian Banks in foreign currency.',
  "PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER-SWIFT": "SWIFT code of beneficiary’s bank",
  "PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER-FILIAL": "Branch",
  "PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER-REKVIZ": "Intermediary bank details",
  LIMITS_PAYMENTS: "Payments",
  LIMITS_TO_CLIENT: "To KICB customers",
  LIMITS_EXCHANGE_STANDART: "Currency exchange at the standard rate",
  LIMITS_EXCHANGE_SPECIAL: "Currency exchange at special rate",
  LIMITS_MPC: "Transfers to the cards of other banks",
  LIMITS_GROSS: "To other banks within KR in KGS (Gross)",
  LIMITS_GROSS_CLEARING: "To another bank in KGS within KR",
  LIMITS_CLEARING: "To other banks within KR in KGS (Clearing)",
  LIMITS_OPEN: "Open deposit",
  LIMITS_ADD: "Deposit replenishement",
  LIMITS_SYSTEM_OF_FAST_OPENINGS: "Instant money transfers",
  LIMITS_SWIFT: "Abroad - SWIFT ",
  REASON_FOR_REISSUE: "Reason for reissue",
  EXPIRATION_CARD: 'Expiration of the card',
  LOSS_THEFT_DAMAGE_OTHER: 'Loss/steal/damage/other',
  SELECT_ALL: 'Choose all',
  NO_NOTIFICATIONS: 'No notifications',
  CARD_BLOCKED: 'Blocked',
  SETTING_CHANGE_PASSWORD: 'Change password',
  SETTING_CHANGE_LOGIN: 'Change login',
  CHANGE_BUTTON: "Edit",
  COMMISSION: 'Fee',
  ADDRESS: 'Address',
  SFKP: '№ SFKR',
  VALUE_DATE: 'Value Date',
  DOCUMENT_NO: 'Document No.',

  // Витрина - Открытие вклада
  TERMS_OF_AGREEMENT_TITLE: "Terms of agreement",
  MAINPAGE_TRANSACTIONS_CONFIRMATION: "Transactions on confirmation",
  CLEARING: 'Clearing',
  GROSS: 'Gross',
  INTERNAL_TRANSFER: 'Internal transfers',
  CHOOSE_DATE: 'Choose date',
  FOR_AMOUNT_INCLUDE: ({named}) =>  `for ammounts ${named('from') !== '0' ? 'over ' + named('from') + ' \u{E001}' : ''} up to ${named('to')} \u{E001} (inclusive)`,
  NO_TRANSACTION_HISTORY: 'No transaction history',
  RANGE: 'Range',
  CHOOSE_CCY: 'Select currency',
  DOCUMENT_NUMBER: 'Document No.',
  TIME_SENDING_TO_BANK: 'Bank transfer time',
  INTERMEDIARY_BANK: 'Intermediary bank',
  PERSONAL_ACCOUNT: 'Personal account',
  PAYMENTS_AMOUNT: 'Amount of payment',
  FROM: 'From',
  TO: 'To',
  ATTENTION: 'Attention!',
  ENTRANCE: "In order to improve the system security, there is a time limit for the connection session with the system server. If there is no activity for 10 minutes after authorization, the system will automatically shutdown\r connection session.In order to resume work, you need to re-authorize. ",
  RECOVER_PASSWORD: 'To recover a forgotten password, you need to enter: \n<br>' +
    '-login \n<br>' +
    '-phone number\n<br>' +
    '-answer security question\n<br>' +
    '-select a method for obtaining secret code\n',
  DATE_START: "Creation date",
  TRANSLATION_COSTS: 'Translation costs',
  RECIPIENT_BANK_NAME: 'Beneficiary bank name',
  INTERMEDIARY_BANK_NAME: 'Intermediary bank name',
  INTERMEDIARY_BANK_SWIFT_CODE: 'SWIFT-code of intermediary bank',
  RECIPIENT_BANK_SWIFT_CODE: 'Beneficiary bank SWIFT code',
  RECIPIENT_BANK_SWIFT: "SWIFT of the beneficiary's bank",
  RECIPIENT_BANK_ADDRESS: 'Beneficiary bank address',
  SWIFT_RECIPIENT_ACC_NO: "Beneficiary's account / IBAN",
  RECIPIENT_ADDRESS: 'Address of the recipient',
  PAYMENT_PURPOSE: 'Purpose',
  TOTAL_DAILY: "Daily limit",
  TOTAL_MONTHLY: "Monthly limit",
  TOTAL_MIN: "Min. amount for 1 transaction",
  TOTAL_MAX: " Max. amount for 1 transaction",
  VALUE_ABSOLUTE: "Fixed fee",
  VALUE_PRECENT: "Interest fee",
  COMMISSION_MAX: "Maximum",
  COMMISSION_MIN: "Minimum",
  FIX_AMOUNT_PERCENT: "Additional fee",
  TARIFFS_CCY: "Tariff currency",
  APP_VERSION: "Application version",
  OFFER: "Offer",
  PRIVACY_POLICY: 'Privacy policy',
  GO_TO_BANK_SITE: "Go to the bank's website",
  BANK_LICENSE: "Bank license",
  USER_GUIDE: "User's manual",
  CHECKBOOK_ORDER: "Order check book",
  CHECKBOOK_QUANTITY_SHEETS: "Consists of 25 sheets",
  CHECKBOOK_COMMISSION: "Commission for 1 check book",
  CHECKBOOK_TRANSFER_METHOD: "Transfer method of check book",
  CHECKBOOK_TRUST_TITLE: "We trust to receive the check book to employee",
  CHECKBOOK_TRUST_NAME: "Full name of the trusted employee",
  CHECKBOOK_TRUST_PASSPORT_WHO: "Issued by",
  CHECKBOOK_TRUST_PASSPORT_WHEN: "Date of issue",
  BANK_BRANCH: "Bank branches",
  CHOOSE_BANK_BRANCH: "Select the bank branch",
  BY_MAIL: "By mail",
  BY_COURIER: "By courier",
  COMMISSION_WRITE_OFF_ACCOUNT: "Fee write-off account",
  CONTACT_PHONE_NUMBER: "Contact phone number",
  ACCEPT_TERMS: "I accept the terms of the Agreement",
  TOTAL_COST: "Total cost",
  SETTING_PIN_CODE: "Set PIN",
  RESERV_SAFEBOX: "Safe deposit box reservation",
  RESERV_SAFEBOX_SIZE: "Size of the safe deposit box",
  RESERV_SAFEBOX_TERM: "Rent period",
  RESERV_SAFEBOX_AMOUNT: "Rent price",
  BOND_PURCHASE: "Buy bonds",
  BOND_ISSUE_NUMBER: "Bond issue number",
  BOND_NOMINAL_AMOUNT: "Nominal value",
  BOND_DATES_PAYMENTS: "Date of interest payment",
  BOND_EFFECTIVE_RATE: "Effective rate",
  BOND_MATURITY: "Maturity ",
  BOND_SALE_PERIOD: "Terms of sale",
  BOND_PURCHASE_QUANTITY: "Number of acquired bonds",
  DEPOSIT_TERM: "Deposit term",
  DEPOSIT_RATE: "Interest rate",
  DEPOSIT_REPLENISHMENT: `Performed operations on "KICB" system   cannot be canceled, therefore, please \nbe careful when sending transactions; It's allowed to replenish only savings and children\n type of deposits;  Replenishment is carried out if there are funds on the current / card account of the holder in\n the currency of the open deposit; The limits on replenishment of deposits can be found in the section \" Limits\"`,
  DEPOSIT_TERMINATE_INFO: "Upon termination, the previously accrued interest will be canceled in accordance with the terms of the agreement.",
  DEPOSIT_TERMINATE_SUCCESS_INFO: "Your application will be processed within 2 banking days.",
  DISCHARGE_NO_TRANSACTION: "During this period you didn't have any transactions",
  DISCHARGE_TWODAYS: "For last 2 days",
  DISCHARGE_WEEK: "For last week",
  DISCHARGE_MONTHLY: "For last month",
  LIMITS_CURRENT: "Current",
  LIMITS_STANDARD: "Standard",
  LIMITS_INCREASED: "Increased",
  LIMITS_ANOTHER: "Another",
  CONFIRMATION_OF_APPLICATION: 'Confirmation of the application',
  AMOUNT_CREDIT: 'Amount to be credited',
  ACCOUNT_CREDIT_NO: 'To account',
  ACCOUNT_DEBIT_NO: 'From account',
  periodicity: 'Periodicity',
  SUCCESS: "Accepted",
  DELETED: 'Canceled',
  ON_CONFIRMATION: 'On confirmation',
  DECLINED: 'Rejected',
  FAILURE: "Not accepted",
  SERVICE: 'Accepted for processing',
  IN_PROCESS: 'Accepted for processing',
  CONFIRMED: 'Confirmed',
  WAITING: 'Waiting',
  STATUS_DICLINE: 'Rejected',
  APPLICATION_ACCEPTED_FOR_PROCESSING: 'Thank you! Application is accepted for processing',
  FINAL_STATUS_OPERATION: "It's required to view the final status of transactions in the History",
  TERM_PREPRAING_CHECKBOOK: 'The term for checkbook preparing  is 1 business day. Responsible specialist will contact you',
  ACCOUNT_STATUS_BLOCKED: 'Blocked',
  CARD_EXPIRATION: 'Card expiration',
  END_DEPOSIT: 'End of deposit',
  UPDATE_PASSPORT_DATE: 'Renew your passport',
  VALIDITY_PERIOD_PASSPORT: 'The validity period of the passport is up to',
  PASSPORT_EXPIRATION_DATE:  'After the expiration of the passport, the user will be transferred to view mode.',
  WILL_BE_BLOCKED: 'will be blocked',
  PASSPORT_DATE_UP_TO: 'Passport validity up to',
  HOME: 'Home',
  ARCHIVE_IS_EMPTY: 'Archive is empty',
  SET_MAIN_ACCOUNT_BY_DEFAULT: 'The current account is set by default',
  SET_MAIN_ACCOUNT_BY_NOT_DEFAULT: 'Current account is no longer default',
  SET_ACCOUNT_NAME_SUCCESS: 'Account is renamed',
  PAYMENT_CAUSE: 'Reason',
  AMOUNT_DEBIT: 'Transfer amount',
  USER_PROFILE: 'User profile',
  CARD_ACCOUNT: 'Card account',
  OPERATIONS_MANAGEMENT_OF_KICB: 'Operations Management of CJSC "KICB"<br>Kyrgyz Republic, Bishkek, Erkindik Boulevard 21',
  FINAL_PIN_CODE: 'For the final setting of the PIN,<br>'+
  'you need to go to ATM and perform any action with the card.<br>'+
  'For security reasons, do not share the code with strangers.',
  ENTER_CHANGE_LIMIT: 'Enter change limit',
  MAXIMUM_AMOUNT: 'Maximum amount',
  NUMBER_OF_OPERATIONS: 'Number of operations',
  CHECKOUT_OPERATION: 'Cash operation',
  ONLINE_SHOPPING: 'Internet shopping',
  POS_TERMINALS: 'POS terminals',
  CARD_REPLENISMENT: 'Card replenishment',
  SET_ONLINE_PAYMENTS_ON: 'Internet payments connected successfully',
  SET_ONLINE_PAYMENTS_OFF: 'Internet payments disabled successfully',
  CARD_WILL_BE_BLOCKED: 'The card will be blocked within 5-15 minutes',
  CARD_WILL_BE_UNBLOCKED: 'The card will be unlocked within 5-15 minutes.',
  SMS_NOTIFICATIONS_ON: 'SMS notifications connected successfully',
  SMS_NOTIFICATIONS_OFF: 'SMS notifications disabled successfully',
  SELECT_DEPOSIT_TYPE: 'Select the type of deposit',
  SELECT_DEPOSIT_TERM: 'Select the term of the deposit',
  DATE_OF_BIRTH: 'Date of Birth',
  DATE_OF_BIRTH_CHILD: "Child's date of birth",
  BIRTH_CERTIFICATE: "Birth certificate",
  CHILD_DATA: "Child data",
  SEND_FOR_CONFIRMATION: 'Send for confirmation',
  ABOUT_TRANSFER: 'About transfer',
  EXECUTOR: 'Executor',
  STATUS_SIGNATURE_1: 'Signature status 1',
  STATUS_SIGNATURE_2: 'Signature status 2',
  RECIPIENT: 'Recipient',
  RECIPIENT_BANK: 'Bank of recipient',
  PURPOSE_OF_PAYMENT: 'Purpose of payment',
  ACCOUNT_NUMBER_IBAN: 'Account number / IBAN',
  CORRESPONDENT_BANK: 'Correspondent bank',
  COMMISSION_TYPE: 'Commission type',
  COMMISSION_WITHHOLD: 'Withhold the transfer fee',
  TOTAL_FOR_CHARGE: "Total to write-off",
  TRANSLATION_COSTS_REFERENCE: "“OUR” at the expense of the sender; </br> “BEN” - at the expense of the beneficiary Field (only for USD).",
  IBAN_OR_ACCOUNT: 'IBAN / account',
  DETAIL_TRANSFER: "Transfer details",
  INTERMEDIARY_BANK_SWIFT: "Intermediary bank SWIFT",
  KPP: "KPP",
  BIN: "BIN",
  KBE: "KBE",
  KNP: 'KNP',
  CORRESPONDENT_ACCOUNT: 'Correspondent account',
  NAME_BANK: 'Name of the bank',
  ADDRESS_BANK: "The bank's address",
  SWIFT_OR_BIK: 'SWIFT / BIK',
  SEARCH_BY: 'Search by:',
  SEARCH_CORP_HISTORY: 'Search',
  NO_MATCHES: 'No matches',
  EXECUTION_DATE: 'Execution date',
  ORDER_DEBIT_CARD: 'Apply for a debit card',
  SELECT_CARD_TYPE: 'Select card type',
  NAME_AND_SURNAME_LAT: 'Name and surname of the cardholder in Latin',
  NAME_AND_SURNAME: 'Name and surname',
  CODE_WORD: 'Codeword',
  APPLICATION_INFO: 'Application information',
  CURRENCY_CARD: 'Card currency',
  CARD_OWNER: 'Card holder',
  DELIVERY_TYPE: 'Delivery type',
  INFO_ACCOUNTS_AND_BALANCES: 'Statement on accounts and balances',
  HELP_LANGUAGE: 'Certificate language',
  RUSSIAN: 'Russian',
  ENGLISH: 'English',
  COMMISSION_FOR_HELP: 'Certificate fee',
  TYPE_HOW_GET_HELP: 'How to receive certificate',
  HELP_SUCCESS_INFO: 'The term for certificate preparing is 1 business day',
  APPLICATION_ACCEPTED: 'Your application has been accepted for work',
  BANK_WILL_CONTACT_SHORTLY: 'A bank employee will contact you shortly',
  MESSAGE: 'Message',
  QUESTION_CHANGED_SUCCESS: 'Security question is successfully changed',
  LOGIN_CHANGED_SUCCESS: 'Login is successfully changed',
  ENTER_NAME_PAYMENT: 'Enter the name of the payment',
  PAYMENT_ACCOUNT: 'Payment account',
  CREATE_TEMPLATE: 'Create template',
  NAME_TEMPLATE: 'Template name',
  WANT_TO_DELETE_PAYMENT_SCHEDULE: 'Are you sure you want to delete a scheduled payment?',
  WANT_TO_DELETE_TEMPLATE: 'Are you sure you want to delete the template?',
  NAME_TEMPLATE_CHANGED_SUCCESS: 'Your template is renamed',
  TEMPLATE_DELETE_SUCCESS: 'Your template is deleted',
  PAYMENT_SCHEDULE_DELETED_SUCCESS: 'Your scheduled payment is deleted',
  TEMPLATE_SAVED_SUCCESS: 'Template is saved',
  CREATE_PAYMENT_SCHEDULE: 'Creating a payment on a schedule',
  EDITING_PAYMENT_SCHEDULE: 'Editing a payment on a schedule',
  SCHEDULE_SAVED_SUCCESS: 'Scheduled payment saved',
  SCHEDULE_CHANGED_SUCCESS: 'Your scheduled payment is changed',
  SELECT_DATES_PAYMENTS_UP_TO_10: 'Select specific dates for making payments. You can choose up to 10 dates.',
  NO_REPETITIONS: 'No repetitions',
  MONDAY: 'Monday',
  TUESDAY: 'Tuesday',
  WEDNESDAY: 'Wednesday',
  THURSDAY: 'Thursday',
  FRIDAY: 'Friday',
  SATURDAY: 'Saturday',
  SUNDAY: 'Sunday',
  SELECT_DAY: 'Choose a day',
  PAYER_BENEFICIARY: 'Sender/Beneficiary',
  REQUISITES_BANK_KGS: `CJSC Kyrgyz Investment and Credit Bank, Bishkek Kyrgyz Republic <br> BIC`,
  REQUISITES_BANK_RUB: 'CJSC Kyrgyz Investment and Credit Bank - SWIFT: KICB KG 22 <br> Bishkek, Kyrgyzstan',
  REQUISITES_BANK_KZT: 'CJSC Kyrgyz Investment and Credit Bank - SWIFT: KICB KG 22 <br> Bishkek, Kyrgyzstan',
  REQUISITES_BANK_ANY: 'CJSC Kyrgyz Investment and Credit Bank <br> SWIFT: KICB KG 22 <br> Bishkek, Kyrgyz Republic',
  PIN_CODE_NOT_MATCH: 'The PIN code does not match. try again',
  SEND_ANOTHER_TRANSFER: 'Send another transfer',
  gross_title: "CLEARING transfers are accepted by the Bank until 11:00 of the Bank's business day. The approximate time for crediting funds to the beneficiary's account in another Bank after 15:00 on the Bank's business day." +
"<br /> Transfers via the GROSS system (urgent transfers) are accepted by the Bank until 15:00 on the Bank's business day. The approximate time for crediting funds to the  recipient in another Bank within 10-30 minutes if the transfer is sent on the Bank's business day before 15:00." +
  'Attention! It is imperative to   check the status of the transaction in the History of Transactions on the day the transfer is made.',
  DATE_CANNOT_BE_LATER: 'Date cannot be more than 5 days from current date.\n',
  SELECT_RENTAL_PERIOD: 'Choose the rental period',
  THANK_YOU_REQUEST_ACCEPTED: 'Responsible specialist will contact you',
  DEPOSIT_AMOUNT: 'Deposit amount',
  CHILD_NAME: "Child's name",
  TITLE_IPC: "Transfers to Elkart cards",
  TITLE_KITEP: 'Жаны Китеп',
  TITLE_DEAL: 'Currency exchange. Deal',
  TITLE_WALLET: 'Elsom wallet replenishment',
  TITLE_CARD_OPENING: 'Getting a debit card',
  TITLE_CARD_REOPENING: 'Card reissue',
  DEFAULT_HISTORY_TITLE: 'Unknown transfer',
  TRANSFER_CLEARING_GROSS: "Transfer type",
  CLOSE: 'Close',
  SELECTED_DATES: 'Appointed dates',
  NUMBER_OF_MONTH: "Number of month",
  SENDER_NAME: "Sender's name",
  CODE_KNP: 'Payment code',
  TRANSFER_PURPOSE_TEXT: 'Appointments',
  CONTRACT_REF_NO: 'Contract number',
  district: 'District or city',
  VO_CODE: 'VO code',
  SCHOOL_CODE: 'School code',
  FULL_NAME_STUDENT: 'Full name of the student',
  ACADEMIC_YEAR: 'Academic year',
  CLASS: 'Class',
  VEHICLE_NUMBER: 'State number',
  PAYMENT_CODE: 'Payment code',
  DEPOSIT_MAIN_INT_TYPE: 'Interest payment',
  EVENTS: 'Events',
  LIMIT_CHANGED_1_HOUR: 'The limit will be changed within 1 hour',
  LICENSE: ' All rights reserved. Licensed by NBKR #046',
  LOANS_TO_DATE: ({named}) => `till ${named('date')}`,
  INFO_TAX: 'To pay tax you need to indicate:'+
  '<br />–TIN'+
  '<br />–location / place of registration of a property or economic activity (region, district, if there is an aiyl aimak);' +
  '<br />–state number of the vehicle when paying transport tax; '+
  '<br />–the amount of tax payable.' +
  "If you have incorrectly indicated the type of tax or one of the above details, KICB CJSC is not responsible. You need to contact the tax authority. In the event of an overpayment, the surplus of the tax amount paid remains on the taxpayer's personal account. Also KICB CJSC strongly recommends to make a copy of the receipt after paying tax in order to ensure its safety. For timely crediting of funds to your personal account, pay tax in advance. You can check the fact of the tax payment made through the electronic service, provided on the website of the STS under KRG <a href='#' class='local-link local-link--dark local-link--underline'>(www.sti.gov.kg).</a>",
  OPENING_DEBET_CARD: 'Opening a debit card',
  CARD_PRODUCTION_TIME: 'You will receive notification. Card production time is 5-7 working days.',
  SEND: 'Send',
  SMS_NOTIFICATION: 'Attention! After activating this service commission will be debited according to the tariffs of the Bank.',
  REPAYMENT_SCHEDULE_LOAN: 'In the case of loan restructuring with interest repayment, it is necessary to obtain a new "Repayment schedule" loan in the Bank.',
  TRANSFER_CONFIRMATION: 'Transfer confirmation',
  TRANSACTIONS_SUCCESS_CONFIRMED: 'Transactions successfully confirmed',
  REJECT: 'Reject',
  NOT_VERIFIED: 'Not verified',
  PAYMENTS_PROVIDERS: 'Payments to service providers',
  PAYMENTS_SALARY_IMPORT: 'Importing - documents',
  LOAN_REFERENCE: 'Loan certificate',
  LOAN_ACCOUNT: 'Loan account',
  STATEMENT_TYPE: 'Certificate type',
  SELECT_LOAN: 'Select loan',
  NUMBER_OF_CHECKBOOKS: 'Number of checkbooks',
  RECIPIENT_FIO: "Recipient's full name",
  SENDER_FIO: 'Sender\'s full name',
  TRANSACTION_DETAILS: 'Transfer details',
  CAR_LICENSE_PLAT: "Car state number",
  REGION_OR_CITY: "Region or city",
  DISTRICT_OR_CITY: 'District or city',
  STREET: 'Street',
  MAILBOX: 'PO Box',
  REGISTERED_ADDRESS: 'Registration address',
  ACTUAL_ADDRESS: 'Actual address',
  SELECT_REGION_OR_CITY: "Select region or city",
  CALCULATE_TAX: "Calculate tax",
  VEHICLE_TYPE: "Type of transport vehicle",
  SELECT_VEHICLE_TYPE: "Select type of transport vehicle",
  ENGINE_CAPACITY: "Engine volume, cm3",
  YEAR_OF_EDITION: "Year of issue",
  SELECT_YEAR_OF_EDITION: "Select year of issue",
  SELECT_YEAR: "Select year",
  SELECT_COEFFICIENT: "Select coefficient",
  SELECT_BASIC_TAX_VALUE: "Select your base tax value",
  CERTIFICAT_FEE: "Certificate fee",
  DELIVERY_FEE: "Delivery fee",
  HOW_TO_RECEIVE: "How to receive",
  COURIER: "Courier",
  DATA_TRUST_USER: "Details of trusted employee",
  SELECTED_ACCOUNTS: "Selected accounts",
  REGISTRATION_ELSOM: 'Registration ELSOM',
  LINK_ELSOM: 'Link ELSOM',
  SEND_SMS_FOR_CONFIRMATION: 'Send SMS for confirmation',
  BREAK_AFTER_MINUTES: ({named}) => `Break in ${named('minutes')} minutes`,
  TO_LEARN_MORE: 'To learn more',
  SELECT_AIMAK: 'Select aimak',
  CURRENCY_TRANSACTION_CODE_VO_REFERENCE: "VO code - a 5-digit code of currency transaction, which is indicated in transactions between a resident and a non-resident of Russia. The code defines the type (purpose) of the transfer.",
  KPP_REFERENCE: "KPP - code, which consists of 9 digits, where there is encrypted information about the organization registration in the Tax Service of the Russian Federation.",
  BIN_REFERENCE: "BIN - a unique number generated for a legal entity and an individual entrepreneur carrying out activities in the form of a joint entrepreneurship in the territory of the Republic of Kazakhstan.",
  KBE_REFERENCE: "Beneficiary Code consists of two digits: the first digit indicates whether the beneficiary is a resident of the Republic of Kazakhstan, the second indicates the sector of the economy to which it belongs",
  KNP_REFERENCE: "KNP - Payment purpose code - a three-digit numeric code designation of the payment purpose",
  ATTENTION_SCHEDULED_PAYMENTS: 'Attention! Payments in those months, in which there are no this date, will be produced on the last day of the month.',
  FIELD_START_128: 'field must start with "128"',
  FIELD_NEED_16_SYMBOLS: 'Field length must be 16 numbers.',
  BENEFICIARY_BANK: 'Beneficiary bank',
  NAME_OF_PAYMENT_BY_CLASSIFIER: 'Name of payment by classifier',
  PAYMENT_TYPE: 'Payment type',
  FEE_AND_SALES_TAX: 'Fee and sales tax',
  RECIPIENT_ACCOUNT_NUMBER: "Recipient's account number",
  REQUISITES_RECIPIENT: "Recipient details",
  SELECT_LOAN_CCY: 'Select loan currency',
  PURPOSE_OF_TAKE_LOAN: 'Purpose of obtaining a loan',
  SELECT_PURPOSE_OF_TAKE_LOAN: 'Select purpose of obtaining a loan',
  DETAILS_FOR_PURPOSE_LOAN: 'Clarification of the purpose of obtaining a loan',
  MONTH_SHORT: 'm.',
  YEAR_SHORT: 'y.',
  FREQUENCY_OF_INTERES_PAYMENT: 'FREQUENCY OF INTEREST PAYMENT',
  MONTHLY: 'Monthly',
  AT_END_OF_TERM: 'At the end of the term',
  ENDING_SESSION: 'Ending a session',
  ENDING_SESSION_DETAILS: ({named}) => `I accept the terms of the public offer posted on the website${named('sec')} seconds`,
  LOGOUT_SESSION: 'Logout a session',
  CONTINUE_WORK: 'Continue work',
  ACCEPT_TERMS_TRANSFER_MONEY: ({named}) => ` I accept the terms of the <a target="_blank" href="${named('href')}" class="money-stream-form__agreement-link">Agreement</a>`,
  ACCEPT_TERMS_ELSOM: ({named}) => `I accept the terms of the public offer posted on the website <a target="_blank" href="${named('href')}" class="money-stream-form__agreement-link">www.elsom.kg</a>`,
  MONEY_TRANSFER_RECEIVE_INFO: 'Transfer can be recieved only in KICB branches',
  MONEY_TRANSFER_ACCEPTED_FOR_PROCESSING: 'Accepted for processing',
  COMMISSION_CHECKBOOK_FEE: 'Check book fee',
  ORDER_CARD_FEE: 'Annual card maintenance fee',
  ORDER_CARD_REOPENING_FEE: 'Reissuance fee',
  CONFIRM: 'Confirm',
  SELECT_TRANSFER_CURRENCY:  'Select transfer currency',
  SELECT_COUNTRY: 'Select country',
  SELECT_CITY: 'Select city',
  SELECT_ACCOUNT_COMMISSION: 'Fee write-off account',
  WITHHOLD_FREE_FROM_ACCOUNT: 'Withhold fee from account',
  PAYMENT: 'Payment',
  ATTACH_DOCUMENTS: 'Attach documents',
  EARLY_COMPLETE_TEXT: 'Your application is accepted by the Bank for processing. A bank employee will contact you shortly.',
  CARD_BLOCKED_NO_TRANS_180: ({named}) => `Your account ${named('acc')} will be blocked due to no transactions on it within 180 days.`,
  ACCOUNT_BLOCKED: 'Account blocking',
  PRIVATE_TRANSFER: 'Private transfer',
  SELECT_DISTRICT_OR_CITY: 'Select district or city',
  NO_CURRENCY_RATES: 'No currency rates were found for this pair',
  SELECT_LOAN_TERM: 'Select loan term',
  ELSOM_INFO_INN: 'To register or link a wallet, it is needed correct TIN number specified in the Bank',
  GET_CODE: 'Get the code',
  CATEGORY: 'Category',
  CATEGORIES: 'Categories',
  REPLENISHMENT_ACCOUNT: 'Replenishment',
  INFORMATION_AGREEMENT: 'Hereby I confirm the accuracy of the data specified above and agree to registration',
  SUCCESSFULLY_REGISTRED: 'You have successfully registered in the ELSOM system. Download the ELSOM application and enter the received by SMS one-time code to activate the wallet',
  SET_FOR_CONFIRMATION: 'Sent for approval',
  ENTER_YOUR_PHONE: 'Enter your phone number',
  TRANSACTION_SUCCESSFULLY_REJECTED: 'Transactions successfully rejected',
  TRANSACTIONS_SUCCESSFULLY_CONFIRMED: 'Transactions successfully confirmed',
  LINK_APPLICATION: 'Download mobile application for iOS and Android!\n' +
   'It’s available for download in AppStore and PlayMarket.',
  OUT: 'Cancel',
  SWIFT_TRANSFER: 'SWIFT transfers',
  CLEARING_GROSS_INTERNAL_TRANSFER: 'Clearing/ Gross/ Internal transfers',
  UPLOADING_DOCUMENT: 'Click on "+" to upload documents',
  DOWNLAND_LIST: 'Download the list',
  DOWNLOADING_BATCH_TRANSFER: 'Downloading batch transfers',
  LIST_OF_TRANSLATIONS: 'List of translations',
  DOCUMENT_NUMBER_PLACEHOLDER: 'Document number',
  SEND_TRANSACTIONS_TO_PRINT: 'send transactions to print',
  SEND_TRANSACTIONS_TO_THE_BANK: 'send transactions to the bank',
  SHOW_ALL_TRANSACTIONS: 'show all transactions',
  PRINT: 'print',
  SEND_BANK: 'Send to the bank',
  ALLOWED_TYPES_OF_OPERATIONS: 'Allowed types of transactions',
  ACCOUNTS_TO_VIEW: 'Accounts to view',
  ACCOUNTS_FOR_TRANSACTIONS: 'Accounts for transactions',
  USER_RIGHT: 'User rights',
  READING_MODE: 'Reading mode',
  CREATING_OPERATIONS: 'Creation of operations',
  COORDINATION_OF_OPERATION: 'Reconciler transactions',
  TOKEN: 'Token',
  CONFIRMATION_THE_OPERATION: 'Confirmation of the operation',
  SALARY_IMPORT: 'Salary - Import',
  CONFIRM_SELECTED: 'Confirm selected',
  REJECT_SELECTED: 'Reject selected',
  DOCUMENT_WITH_AN_ERROR: 'Error documents',
  NUMBER_ATTACHED_FILES: 'Quantity of attachments',
  COMMISSION_FROM_ACCOUNT: 'Fee from account',
  CLIENT_CODE: 'Client code',
  APPLICATION_HAS_BEEN: 'Your application has been accepted by the Bank for processing. Certificate preparation time 1 business day.',
  APPLICATION_HAS_BEEN_CORP: 'Certificate preparation time 1 business day.',
  APPLICATION_CHECK_BOOK_CORP: 'Preparation time 1 business day.',
  BUY_BONDS_CORP: 'Your application has been accepted by the Bank for processing.',
  YOU_ARE_WELCOME: 'Welcome to KICB support service.',
  ACCEPTANCE_TIME:'Acceptance time until',
  IAM_FAMILIAR_TERMS: 'I am familiar with the terms of the transfer',
  LINK_PHONE_NUMBER_TO_VISA_ALIAS: 'Visa Direct',
  CONFIRMATION_CARD_BINDING: 'Confirm mobile link',
  CARD_BINDING_DESCRIPTION: 'This will link your mobile number with Visa card for receiving payments. Any previous mobile and card linkage will be overridden.',
  READY_SEND_VISA_ALIAS: 'You’re all set to pay, send, and receive funds with your KICB card with Visa Direct.',
  YOUR_MOBILE_NUMBER: 'Your mobile number',
  YOUR_NAME_BE_DISPLAYED: 'Your name will appear as',
  SEND_FUNDS_VIA_MOBILE: 'when you are receiving funds with your mobile number.',
  LINKED_CARD: 'Linked card',
  YOU_ACTIVATED_ONE_CARD: 'You have enabled 1 KICB card for Visa Direct',
  LINKED_MOBILE_PHONE_NUMBER: 'Linked mobile number',
  NAME_ACCOUNT: 'Name on account',
  FOUND_SENT: 'Funds sent to your mobile number will be credited into your linked card',
  DONE: 'Done',
  VISA_ALIAS_ATTENTION:  ({named}) =>  `Your mobile phone number is already linked to Visa Direct on another card (${named('bankName')}). Would you like to link to this card?`,
  LOGIN_VIA_QR: 'Quick entry by QR code',
  TIMER_UPDATE_QR_CODE: ({named}) => `Retry QR code request after ${named('sec')} seconds`,
  GOLD_CROWN: 'Tariffs for money transfer system “Zolotaya Korona"',
  COLD_CROWN_PAYMENT: ' You can read the tariffs for money transfer system  "Zolotaya Korona”',
  GOLDEN_CROWN_THREE: 'You can find money transfer pick-up points here.',
  TOTAL_AMOUNT: "Total amount",
  NUMBER_OF_TRANSACTIONS: "Number of transactions",
  CVC: "CVC",
  CARD_EXPIRATION_DATE: "MM/YY",
  CARD_VISA_EXPIRATION_DATE: "MM/YY",
  CARD_NO: "Card number",
  GENERATE_PAYMENT_CODE: "Generate a payment code",
  SALYK_INFO: "Further, information from State Tax Service will be only in Russian language",
  INDIVIDUAL_ENTREPRENEUR: "Individual entrepreneur",
  MY_QR: "My QR",
  GENERATE_QR: "Generate QR for point of sale",
  NAME_QR: "Name of the point of sale",
  ENTER_DATA: "Enter the data",
  ADD: "Add",
  VIEW_QR: "View QR",
  QR_TURNOVERS: "QR turnovers",
  ADMINISTRATION: "Administration",
  TITLE_QR: "Title",
  DO_YOU_REALLY_DELETE_QR: "Do you really want to delete QR?",
  IN_MY_QR: "Return to my QR",
  NOT_SPECIFIED: "Not specified",
  STATEMENT_FOR_LAST_24_HOURS: "Statement for the last 24 hours",
  NO_STATEMENT: "No statement",
  SELECT_FROM_LIST: "Select from the list",
  LINKED_QR: "Linked to QR",
  INACTIVE: "Inactive",
  CHECK_DATA_CHANGING: "Check the data before changing",
  LINKED_USER: "Linked users",
  SELECT_WILL_BE: "The users you select will be transferred to the “linked”  status",
  LINKED: "linked",
  DELETE_USER: "Deleted users",
  UNTETHERED: "untethered",
  QR_SUCCESSFULLY_DELETED: "QR successfully deleted",
  CHOOSE_ACCOUNT: "Choose account",
  CONTINUE: "Continue",
  DONT_HAVE_ACTIVE_QR: "You don't have active QR",
  CHECK_DATA_BEFORE_ADDING: "Please check the data before adding",
  SELECT_USER_WHO: 'You can select one or more users who will be granted access to view incoming payments via QR' +
    '<br> \n' + 'If you did not find the user you need in the specified list, you should register him/her at the Bank branch',
  QR_GEBERATION_ERROR: "QR generation is available only to users with signature rights ",
  PAYMENT_ELQR: 'Payment via QR',
  EDITING_USERS: "Editing users",
  SELECT_USER_LINK: "Select user(s) to link/unlink from QR",
  EMPLOYEE_NOT_SELECTED: "Employee not selected",
  SAVE_FOR_PRINTING: "Save for printing",
  RETURN_TO_QR_LIST: "Return to QR list",
  SUCCESSFULLY: "Successfully",
  AMOUNT: "turnover by QR in 24 hours",
  MY_POS: "My POS",
  QR_TRANSLATION: "QR Translation",
  OPENING_AN_ACCOUNT: "Opening a new account",
  CURRENCY_RUSSIAN_RUBLE: "Russian ruble",
  CURRENCY_KAZAKH_TENGE: "Kazakh tenge",
  CURRENCY_TURKISH_LIRAS: "Turkish liras",
  CURRENCY_CHINESE_YUAN: "Chinese yuan",
  CURRENCY_EURO: "Euro",
  CURRENCY_POUND: "Pound sterling",
  CURRENCY_SWISS_FRANC: "Swiss franc",
  CURRENCY_USA_DOLLAR: "US dollar",
  OPENING_ACCOUNT: "Opening an account",
  CURRENCY_KYRGYZSTAN_SOM: "Кыргыз сому",
  OPEN_ACC: "Open an account",
  CREATE_AN_INVOICE_WITH_QR: "Create invoice with QR",
  CREATING_INVOICE_WITH_QR: "Creating invoice with QR",
  SELECT_ACCOUNT_FUNDS_SHOULD_RECEIVED: "Select the account where the funds should be received",
  SELECT_TYPE_CREATE: "Select type",
  MANUALLY: "Manually",
  AUTOMATICALLY: "Automatically",
  INVOICE: "Invoice No",
  CLIENT_NAME: "Client name",
  CLIENT_DETAILS: "Client details",
  NUMBER_ACCOUNT: "Account No.",
  TOTAL_AMOUNT_INVOICE: "Total amount",
  SELECT_FILE_UPLOAD_FORMAT: "Download a file in one of the formats listed below. For information about the format, click the \"?\" button.",
  QUANTITY: "Quantity",
  PRICE: "Price",
  ADDED_MORE: "Add more",
  FILE_PREVIEW: "Viewing files for download",
  NAME:  "Name",
  YOU_DONT_HAVE_RIGHTS: "You don't have access rights",
  UPLOAD_THE_FILE_OF_FOLLOWING: "Download a file in one of the formats listed below. For information about the format, click the ? button.",
  SELECT_ACCOUNT_FUNDS_SHOULD_RECEIVED2: "Select account where the funds should be received\n",
  ADDRESS_QR: "Address of the point of sale",
  CREATING_INVOICE_WITH_QR_CODE: "Creating invoice with QR"
}














