export default {
  AUTH_GREETINGS: "Добро пожаловать в интернет-банкинг.",
  AUTH_LOGIN: "Логин",
  AUTH_PASSWORD: "Пароль",
  AUTH_BUTTON: "Войти",
  AUTH_PASWORDRESET: "Забыли пароль?",
  AUTH_REGISTRATION: "Регистрация",
  AUTH_DISCLAIMER: "Внимание! ЗАО «KICB» предупреждает:  Если Вы используете чужой компьютер, рекомендуется включать режим приватного просмотра страниц.  В адресной строке или в правом нижнем углу браузера должен быть значок закрытого замка 🔒. Он означает, что Ваше интернет-соединение защищено. Подробнее об этом читайте в разделе Безопасность.  Банк никогда не потребует подтвердить пароль и логин через электронные сообщения. Если Вы получили подозрительное сообщение, запрашивающее Ваши личные данные, логин и пароль — проигнорируйте его.  О подобных случаях просим сообщать на почту ibank@kicb.net или в круглосуточный Call-Центр: +996 (312) 620 101",
  AUTH_CALLCENTRE: "Круглосуточный Call-центр",
  AUTH_COPYRIGHTFOOTER: "2022, Кыргызский инвестиционно-кредитный банк (KICB) Все права защищены. Лицензия НБКР № 046",
  LOGIN_GREETINGS: "Вход в интернет-банкинг",
  LOGIN_CODEHASBEENSENT: "Вам выслан код на номер",
  LOGIN_RETRYSMS: (data) => `${'Повторить отправку SMS'} ${data.named('count') ? 'через' : ''}`,
  LOGIN_EMAIL: "Получить код подтверждения на e-mail",
  LOGIN_BUTTON: "Подтвердить",
  MAINPAGE_NATURALPERSON: "Физическое лицо",
  MAINPAGE_ENTITYPERSON: "Юридическое лицо",
  NO_TRANSACTION: 'Нет транзакции',
  MAINPAGE_ACCOUNTS: "Счета",
  MAINPAGE_PAYMENTS: "Платежи",
  MAINPAGE_HISTORY: "История",
  MAINPAGE_SHOWCASE: "Витрина",
  MAINPAGE_MESSAGES: "Сообщения",
  MAINPAGE_PROFILE: "Профиль",
  MAINPAGE_ARCHIVE: "Архив",
  MAINPAGE_CARDS: "Карты",
  MAINPAGE_ACCOUNTTYPE: "Тип счета",
  MAINPAGE_BALANCE: "Баланс",
  MAINPAGE_DETAILS: "Реквизиты",
  MAINPAGE_BANKSTATEMENT: "Выписка",
  MAINPAGE_OPENACCOUNT: "У вас нет открытых счетов",
  MAINPAGE_OPENCARD: "Открыть карту",
  MAINPAGE_DEPOSITS: "Вклады",
  MAINPAGE_DEPOSIT: "Вклад",
  MAINPAGE_OPENDEPOSIT: "Открыть вклад",
  MAINPAGE_DEPOSITNAME: "Наименование вклада",
  MAINPAGE_ACCRUED: "Начисленные %",
  MAINPAGE_REPLENISH: "Пополнить",
  MAINPAGE_LOAN: "Кредиты",
  TYPE_LOAN: 'Тип кредита',
  TYPE_DEPOSIT: 'Тип вклада/Контракт',
  // CONTRACT : 'Контракт',
  MAINPAGE_GETLOAN: "Открыть кредит",
  MAINPAGE_GETLOANDETAILS: "Получите деньги в кредит",
  MAINPAGE_LOANNAME: "Наименование кредита",
  MAINPAGE_LOANSUM: "Сумма",
  MAINPAGE_LOANREPAYMENT: "К погашению",
  MAINPAGE_LOANLEFTOVER: "Остаток",
  MAINPAGE_LOANSCHEDULE: "График",
  MAINPAGE_LOANINTERESTRATE: "ставка",
  MAINPAGE_EXCHANGERATE: "Курсы валют",
  MAINPAGE_NOCASH: "Безналичные",
  MAINPAGE_CASH: "Наличные",
  MAINPAGE_CURRENCY: "Валюта",
  MAINPAGE_BUYCURRENCY: "Покупка",
  MAINPAGE_SELLCURRENCY: "Продажа",
  MAINPAGE_NBKR: "НБКР",
  MAINPAGE_CROSSEXCHANGERATE: "Кросс курсы к USD",
  MAINPAGE_GOTOEXCHANGE: "Перейти к обмену",
  MAINPAGE_ELSOM: "Элсом",
  MAINPAGE_RECENTACTIVITES: "Ближайшие события",
  MAINPAGE_ENDOFPOWEROFATTORNEY: "Окончание доверенности",
  MAINPAGE_PASSPORTEXPIRATIONDATE: "Окончание срока действия паспорта",
  MAINPAGE_SEEALLACTIVITIES: "Смотреть все события",
  MAINPAGE_MAP: "Офисы и банкоматы",
  MAINPAGE_ACTIVITYTIME: "Платеж в 08:40",
  MAINPAGE_TEMPLATE: "Быстрая оплата",
  MAINPAGE_TABLECOLUMN_TYPE: "Тип счета",
  MAINPAGE_HEADER_TITLE: "Быстрая оплата",
  MAINPAGE_TABLECOLUMN_BALANCE: "Баланс",
  MAINPAGE_TABLECOLUMN_REQUISITES: "Реквизиты",
  MAINPAGE_TABLECOLUMN_CHECKOUT: "Выписка",
  MAINPAGE_SECTION_ARCHIVE: "Архив",
  MAINPAGE_TABLECOLUMN_TYPEOFCARD: "Тип карты",
  MAINPAGE_TABLECOLUMN_TYPEOFWALLET: "Тип кошелька",
  MAINPAGE_WALLET_TITLE: "Электронные кошельки",
  MAINPAGE_WALLET_JOIN: "Добавить ЭЛСОМ",
  MAINPAGE_WALLET_SUBTEXT: 'Получите доступ к Элсом из "KICB"',
  MAINPAGE_DEPOSITS_NAME: "Наименование вклада",
  MAINPAGE_DEPOSITS_SUM: "Сумма",
  MAINPAGE_DEPOSITS_PERCENT: "Начисленные %",
  MAINPAGE_DEPOSITS_ADD: "Пополнить",
  MAINPAGE_DEPOSITS_RATE: "Ставка",
  MAINPAGE_CARD_ACTION: "Открыть карту",
  MAINPAGE_CREDITS_ACTION: "Получить кредит",
  MAINPAGE_CREDITS_TITLE: "Кредиты",
  MAINPAGE_CREDITS_NAME: "Наименование кредита",
  MAINPAGE_CREDITS_REPAYMENT: "К погашению",
  MAINPAGE_CREDITS_REMAINDER: "Остаток",
  MAINPAGE_CREDITS_GRAPH: "График",
  MAINPAGE_RECENTEVENTS_ITEM: "Выплата по кредиту",
  MAINPAGE_WALLET_MODAL_TITLE: "Добавление кошелька ЭЛСОМ",
  MAINPAGE_WALLET_MODAL_BILL: "Ведите инн",
  PAYMENTS_TRANSFER: "Переводы",
  TOP_UP_ACCOUNT: "Пополнить свой счёт",
  REPLENISHMENT_FROM_VISA: "Пополнение с карты VISA",
  REPLENISHMENT_FROM_VISA_OTHER_BANK: "Пополнение с карты VISA другого банка",
  ELCARD: "Элкарт",
  TRANSFER_TO_VISA: "Переводы на карты VISA других банков",
  PAYMENTS_MYACCOUNTS: "Между своими счетами",
  CARD_VISA_CARD_OCT: "Перевод на карту Visa",
  SALYK_PAYMENT: "Оплата налога на недвижимое имущество",
  PAYMENTS_KICBACCOUNTS: "Клиенту KICB",
  PAYMENTS_OTHERBANKS: "В другой банк по КР в сомах",
  TITLE_CLEARING: 'Клиринг',
  TITLE_GROSS: 'Гросс',
  PAYMENTS_SWIFT: "За рубеж – SWIFT",
  ALL_PAYMENTS: 'Все',
  PAYMENTS_EXCHANGECURRENCY: "Обмен валют",
  PAYMENTS_EXCHANGEDEAL: "Обмен валют. Сделка",
  PAYMENTS_CARD_OTHER_BANK: "Перевод на карту другого Банка",
  PAYMENTS_BATCH_LOADING: "Импорт документов",
  SALARY: "Зарплата",
  PAYMENTS_MONEY_SYSTEM: "Системы денежных переводов",
  PAYMENTS_PAYMENTS: "Платежи",
  PAYMENTS_MOBILE: "Мобильная связь",
  PAYMENTS_TAXES: "Налоги",
  PAYMENTS_FINES: "Штрафы",
  PAYMENTS_GOVERNMENT: "Государственные услуги",
  PAYMENTS_INTERNET: "Интернет",
  PAYMENTS_TV: "Телевидение",
  PAYMENTS_INSURANCE: "Страхование",
  PAYMENTS_UTILITY: "Коммунальные услуги",
  PAYMENTS_ED: "Образование",
  PAYMENTS_FINANCE: "Финансовые услуги",
  PAYMENTS_RENT: "Аренда",
  PAYMENTS_WALLETS: "Электронные кошельки",
  PAYMENTS_FUN: "Развлечение",
  PAYMENTS_CHARITY: "Благотворительность",
  PAYMENTS_MMM: "Сетевой бизнес",
  PAYMENTS_TAXI: "Такси",
  PAYMENTS_ADS: "Реклама",
  PAYMENTS_OTHER: "Прочие",
  PAYMENTS_SEARCH: "Введите название или категорию услуги",
  PAYMENTS_TEMPLATES: "Шаблон перевод между своими счетами",
  PAYMENTS_TRANSFERS: "Перевод между своими счетами",
  PAYMENTS_NOTEMPLATES: "Шаблонов нет",
  PAYMENTSGENERIC_REQUISITES: "Реквизиты",
  PAYMENTSGENERIC_ACCOUNTCREDIT: "Счет списания",
  PAYMENTSGENERIC_ACCOUNTDEBIT: "Счет пополнения",
  PAYMENTSGENERIC_CHOOSEACCOUNT: "Выберите счет",
  PAYMENTSGENERIC_SUMOFTRANSFER: "Сумма перевода",
  PAYMENTSGENERIC_CONFIRMTRANSFER: "Подтвердить перевод",
  PAYMENTSGENERIC_STATUSOFOPERATION: "Статус операции",
  PAYMENTSGENERIC_PERSONALACCOUNT: "Лицевой счёт",
  PAYMENTSGENERIC_CHOOSESERVICE: "Выбор услуги",
  PAYMENTSGENERIC_REQUISITESFILL: "Заполнение реквизитов",
  PAYMENTSGENERIC_CATEGORYSELECTION: "Выбор категории",
  PAYMENTSGENERIC_TAXCALCULATION: "Расчет налога",
  PAYMENTSGENERIC_SUMOFREPLENISH: "Сумма зачисления",
  PAYMENTSGENERIC_CONFIRMPAYMENT: "Подтверждение",
  ACCOUNTDETAILS_SUMINBLOCK: "Сумма в блоке",
  ACCOUNTDETAILSREQUISITES_CLIENT: "Клиент",
  ACCOUNTDETAILSREQUISITES_BANKMEDIATOR: "Банк посредник",
  ACCOUNTDETAILS_RENAME: "Переименовать счет",
  ACCOUNTDETAILS_RENAMEOLD: "Текущее наименование счета",
  ACCOUNTDETAILS_RENAMENEW: "Новое наименование",
  ACCOUNTDETAILS_RENAMESAVED: "Сохранить",
  ACCOUNTDETAILS_BANKSTATEMENT: "Выписка по счету",
  ACCOUNTDETAILS_REQUISITES: "Реквизиты счета",
  ACCOUNTDETAILS_PAYANDTRANSFER: "Оплатить",
  ACCOUNTDETAILS_REPLENISH: "Пополнить свой счет",
  ACCOUNTDETAILSSTATEMENT_CLIENT: "Клиент",
  ACCOUNTDETAILSSTATEMENT_CURRENCY: "Валюта счета",
  ACCOUNTDETAILSSTATEMENT_BALANCE: "Актуальный баланс",
  ACCOUNTDETAILSSTATEMENT_STAMENENTCREATION: "Сформировать выписку",
  ACCOUNTDETAILSSTATEMENT_DOWNLOAD: "Скачать",
  ACCOUNTDETAILSSTATEMENT_PRINT: "Печать",
  ACCOUNTDETAILSSTATEMENT_DATE: "Дата",
  ACCOUNTDETAILSSTATEMENT_CONTREAGENT: "Контрагент",
  ACCOUNTDETAILSSTATEMENT_SUMMART: "Описание",
  ACCOUNTDETAILSSTATEMENT_SUM: "Сумма",
  ACCOUNTDETAILSSTATEMENT_LEFTOVER: "Остаток",
  ACCOUNTDETAILSSTATEMENT_TEXT: "Пожалуйста, проинформируйте нас о несоответствии в выписке по счету в течение 14 дней",
  CARD_DETAILS_TITLE: 'Дебетовая карта',
  CARDDETAILS_LEFTOVER: "Неснижаемый остаток",
  CARDDETAILS_BYDEFAULT: "Карта по умолчанию",
  CARDDETAILS_NFCPAY: "NFC платежи",
  CARDDETAILS_CARDBLOCK: "Блокировка карты",
  CARDDETAILS_INTERNETPAY: "Интернет платежи",
  CARDDETAILS_SMS: "СМС уведомления",
  HEADER_NOTIFICATIONS: "Уведомления",
  CARDDETAILS_RERELEASE: "Перевыпустить карту",
  CARDDETAILS_PINCODE: "Установить PIN код",
  CARDDETAILS_LIMIT: "Управление лимитами",
  CARDDETAILS_SETTINGS: "Настройки",
  CARDDETAILS_REQUISITESCARD: "Реквизиты карты",
  CARDDETAILS_MINISTATEMENT: "Мини выписка",
  CARDDETAILS_STATEMENTPERIOD: "Выписка за период",
  CARDDETAILS_OVERDRAFT: "Запросить овердрафт",
  CARDDETAILS_PAYANDTRANSFER: "Оплатить и перевести",
  CARDDETAILS_REPLENISH: "Пополнить свою карту",
  CARDDETAILSMINISTATEMENT_PLACEDATE: "Место операции / Дата",
  CARDDETAILSMINISTATEMENT_SUMINCURRENCYACCOUNT: "Сумма в валюте списания",
  CARDDETAILSMINISTATEMENT_SUMINCURRENCY: "Сумма в валюте счета на оплату",
  CARDDETAILSMINISTATEMENT_CARDTYPE: "Тип карты",
  CARDDETAILSMINISTATEMENT_AVAILABLEBALANCE: "Доступный баланс",
  CARDDETAILSMINISTATEMENT_PRINT: "Печать",
  DEPOSITDETAILS_PERCENTNOW: "%% на текущий момент",
  DEPOSITDETAILS_PERCENTLATER: "%% к выплате в конце срока",
  DEPOSITDETAILS_OPENDATE: "Дата открытия",
  DEPOSITDETAILS_CLOSEDATE: "Дата закрытия",
  DEPOSITDETAILS_INTERESTRATE: "Процентная ставка",
  DEPOSITDETAILS_NAME: "Наименование",
  DEPOSITDETAILS_SUMOFREPLENISH: "Сумма пополнения",
  DEPOSITDETAILS_ACCOUNTUSED: "Счет списания",
  DEPOSITDETAILS_REPLENISH: "Пополнить",
  DEPOSITDETAILS_RENAME: "Переименовать вклад",
  DEPOSITDETAILS_CURRENTNAME: "Текущее наименование вклада",
  DEPOSITDETAILS_NEWNAME: "Новое наименование",
  LOANDETAILS_REPLENISHLOAN: "Пополнить кредитный счет",
  LOANDETAILS_REQUISITESLOAN: "Реквизиты кредитного счета",
  LOANDETAILS_SCHEDULE: "График погашения",
  LOANDETAILS_SUMOFLOAN: "Cумма кредита",
  LOANDETAILS_LEFTOVEROFMAINSUM: "Остаток основной суммы",
  LOANDETAILS_INTERESTRATE: "Процентная ставка",
  LOANDETAILS_LOAN: "Кредит",
  LOANDETAILS_ACTIONSLOAN: "Действия по кредиту",
  LOANDETAILS_NEXTPAYMENT: "След. платеж: ",
  SHOWCASE_REQUISITIONING: "Оформление заявок",
  SHOWCASE_GETLOAN: "Получить кредит",
  SHOWCASE_GETLOANDETAILS: "Деньги на любые цели от 13%",
  SHOWCASE_OPENDEPOSITDETAILS: "Начните копить прямо сейчас",
  SHOWCASE_GETLOANBUTTON: "Оформить",
  SHOWCASE_OPENDEPOSITBUTTON: "Открыть",
  SHOWCASE_CARDSWALLETS: "Карты и кошельки",
  SHOWCASE_WALLETS: "Кошельки",
  SHOWCASE_ACQUIRING: "Подключить эквайринг",
  SHOWCASE_OPENVIRTUALCARD: "Открыть виртуальную картуг",
  SHOWCASE_OPENDEBET: "Открыть дебетную карту",
  SHOWCASE_BANKPRODUCTS: "Продукты банка",
  SHOWCASE_CHECKBOOK: "Заказ чековой книжки",
  SHOWCASE_OBLIGATIONS: "Приобрести облигации",
  SHOWCASE_CERTIFICATE: "Получить справку по счетам",
  SHOWCASE_SAFECELL: "Забронировать сейфовую ячейку",
  SETTINGS_FIOISNEWFULLNAME: "Ф.И.О.",
  SETTINGS_PASSPORTID: "Номер паспорта",
  SETTINGS_EXPIRYDATE: "Дата истечения",
  SETTINGS_PROPISKA: "Адрес по прописке",
  SETTINGS_FACTUAL: "Адрес фактический",
  SETTINGS_PHONENUMBER: "Номер телефона",
  SETTINGS_SETTINGSCEPTION: "Настройки",
  SETTINGS_LIMITS: "Лимиты",
  SETTINGS_COMPANY: "Настройки компании",
  COMPANY: 'Компания',
  USER: 'Пользователи',
  NO_EVENTS: 'Нет событий',
  PAYMENT_TYPE_CORP_TRANSACTIONS: 'Тип платежа',
  DATE_CREATION_TABLE: 'Дата создания',
  APPOPINTMENT: 'Назначения',
  STATUS_SENT: 'Статус /Отправлен',
  CREACTED_SIGNED: 'Создан / Подписан',
  DOCUMENT_DATE: 'No Документа / Дата',
  FORM_OPERATION: 'На счет / Тип операции',
  NO_ACTIVE_CARD: 'Нет активных карт',
  NO_DEPOSITS: 'Нет вкладов',
  NO_LOAN: 'Нет кредитов ',
  SETTINGS_TARIFFS: "Тарифы",
  SETTINGS_CALENDAR: "Календарь",
  SETTINGS_SCHEDULEDPAY: "Платежи по расписанию",
  SETTINGS_TEMPLATEs: "Шаблоны",
  SETTINGS_TEMPLATEs_ACCOUNTDEBIT: "Счет зачисления",
  SETTINGS_TEMPLATEs_ACCOUNTCREDIT: "Назначение",
  SETTINGS_TEMPLATEs_PURPOSE: "Сумма зачисления",
  SETTINGS_TEMPLATEs_REDO: "Выполнить",
  SETTINGS_TEMPLATEs_CHANGENAME: "Переименовать шаблон",
  SETTINGS_TEMPLATEs_SHEDULE: "Установить расписание",
  SETTINGS_TEMPLATEs_DELETE: "Удалить",
  SETTINGS_TEMPLATEs_CHANGINGNAME: "Переименование шаблона",
  SETTINGS_TEMPLATEs_EDIT: "Редактировать",
  SETTINGS_TEMPLATEs_CANCEL: "Отмена",
  SETTINGS_TEMPLATEs_REPEAT: "Повторять",
  SETTINGS_TEMPLATEs_INDEFINITELY: "Бессрочно",
  SETTINGS_TEMPLATEs_PERIOD: "Периодичность",
  SETTINGS_TEMPLATEs_ONCEAWEEK: "Раз в неделю",
  SETTINGS_TEMPLATEs_FORNIGHTLY: "Раз в 2 недели",
  SETTINGS_TEMPLATEs_FORMONTHLY: "Раз в месяц",
  SETTINGS_TEMPLATEs_FORDATE: "В назначенные даты",
  SETTINGS_TEMPLATEs_SETPERIOD: "Выберите период",
  SETTINGS_TEMPLATEs_DAYOFTHEWEEK: "День недели",
  SETTINGS_HISTORYVHODA: "История входа",
  SETTINGS_LANGUAGECHANGE: "Выбор языка",
  SETTINGS_ABOUTSITE: "О сайте",
  SETTINGS_EXIT: "Выход",
  SETTINGS_PROFILE_CHANGE: "Смена типа аутентификации",
  SETTINGS_PROFILE_REPLACE: "",
  SETTINGS_PROFILE_CHANGE_PASSWORD: "История транзакций",
  SETTINGS_PROFILE_CHANGE_LOGIN: "Назначение платежа",
  SETTINGS_PROFILE_GET_CODE: "Получить код инициализации Google Authenticator",
  SETTINGS_QUESTION_TITLE: "Смена контрольного вопроса",
  SETTINGS_QUESTION_DESC: "Пожалуйста, выберите контрольный вопрос для дальнейшей возможности восстановления забытого пароля",
  SETTINGS_QUESTION_CHOOSE: "Выберите контрольный вопрос",
  SETTINGS_QUESTION_ANSWER: "Ваш ответ",
  SETTINGS_PASSWORD_NOW: "Текущий пароль",
  SETTINGS_PASSWORD_NEW: "Новый пароль",
  SETTINGS_PASSWORD_NEW_CONFIRM: "Повтор нового пароля",
  SETTINGS_LOGIN_NOW: "Текущий логин",
  SETTINGS_LOGIN_NEW: "Новый логин",
  SETTINGS_LOGIN_NEW_CONFIRM: "Повтор нового логина",
  HISTORY_ACCEPT: "Принят",
  HISTORY_NOACCEPT: "Не принят",
  HISTORY_DEPOSIT: "Пополнение депозита",
  HISTORY_DEPOSIT_OPEN: "Открытие депозита",
  BILL_NAME: "Счет",
  BILL_SETTINGS: "Настройки",
  BILL_TITLE: "Расчетный счет",
  TRANSFER_TITLE: "Обмен валют",
  TRANSFER_NAV_FIRST: "Платежи и переводы",
  TRANSFER_TO_CARDS_OTHER_BANKS: "Перевод на карту другого Банка",
  TRANSFER_NAV_SECOND: "Обмен валют",
  TRANSFER_NAVBAR_REQ: "Реквизиты",
  TRANSFER_NAVBAR_CONFIRM: "Подтвердить перевод",
  TRANSFER_NAVBAR_STATUS: "Статус операции",
  TRANSFER_NAVBAR_PAYMENT: "Оплата",
  TRANSFER_BILL_IN: "Счет пополнения",
  TRANSFER_BILL_OUT: "Счет списания",
  TRANSFER_DIRECTION_COUNTRY: "Страна",
  TRANSFER_SELECT_CITY: "Город",
  TRANSFER_DIRECTION_CITY: "Направление-город",
  TRANSFER_DIRECTION_FULL_NAME_RECIPIENT: "ФИО получателя",
  TRANSFER_DIRECTION_FULL_NAME_RECIPIENT_PASSPORT: "ФИО получателя согласно паспорту",
  TRANSFER_EXCHANGE: "Курс обмена",
  TRANSFER_SUM_IN: "Сумма к зачислению",
  TRANSFER_SUM_OUT: "Сумма к списанию",
  TRANSFER_BTN_TEXT: "Обменять",
  TRANSFER_TEMPLATE: "Шаблоны переводов между своими счетами",
  TRANSFER_TEMPLATE_ELCART: "Шаблоны переводов на карты Элкарт",
  TRANSFER_TEMPLATE_VISA: "Шаблоны переводов на карты VISA",
  TRANSFER_TEMPLATE_SBER_BANK: "Шаблоны переводов на карты Сбербанк",
  TRANSFER_AMOUNT_IN: 'Сумма к зачислению',
  TRANSFER_AMOUNT_OUT: 'Сумма к списанию',
  TRANSFER_EXCHANGE_RATE: 'Курс',
  SERVICE_POINTS_FILTER: "Фильтр",
  HEADER_CALLCENTER: "Call-центр",
  PAYMENT_TITLE: "Быстрая оплата",
  PAYMENT_PLACEHOLDER: "Введите название или категорию услуги",
  HISTORY_TITLE: "История транзакций",
  HISTORY_INPUT_USERNAME: "Назначение платежа",
  HISTORY_INPUT_DATE: "Выберите даты",
  HISTORY_INPUT_ACCESS: "Принят",
  HISTORY_INPUT_NOT_ACCESS: "Не принят",
  HISTORY_INPUT_TODAY: "Сегодня",
  MESSAGES_TITLE: "Сообщения",
  MESSAGES_BTN: "Написать сообщение",
  "MESSAGES_CHOSE-THEME": "Выберите тему обращения:",
  "FOOTER_CALL-CENTER": "Круглосуточный Call-центр:",
  WALLETS_DATE_AND_TIME: "Дата и время",
  WALLETS_COUNTERAGENT: "Контрагент",
  WALLETS_DESCRIPTION: "Описание",
  WALLETS_SUM: "Сумма",
  WALLETS_LAST_TRANSACTIONS: "Последние транзакции",
  WALLETS_ADD_BILL: "Пополнить",
  WALLETS_ADD_BILL_CHOOSE: "Выберите счет",
  WALLETS_ADD_BILL_SUBMIT: "Подтвердить",
  WALLETS_ADD_BILL_SCHET: "Счет списания",
  WALLETS_MODAL_INFO: 'Внимание! Данные по кошельку не будут отображаться. Продолжить?',
  WALLETS_MODAL_YES: 'Да',
  WALLETS_MODAL_CANCEL: 'Отмена',
  WALLETS_UNTIE_THE_WALLET: 'Отвязать кошелек',
  WALLETS_SUCCESSFULLY: 'ЭЛСОМ успешно подвязан',
  WALLETS_CONFIRM_OTP: 'Подтверждения',
  WALLETS_UNTIED: ({named}) => `Элсом ${named('phoneNumber')} успешно отвязан`,
  CREDIT_GET_TITLE: "Заявка на получение кредита",
  CREDIT_GET_STATUS: "Статус заявки",
  CREDIT_GET_TYPE_OF_CREDIT_LABEL: "Тип кредита",
  CREDIT_GET_TYPE_OF_CREDIT_INPUT: "Выберите тип кредита",
  CREDIT_GET_PHONE: "Номер телефона",
  CREDIT_GET_DOCS: "Сопроводительные документы",
  "PAYMENTS_TRANSFERS_SCHET_LABEL-IN": "Счет списания",
  "PAYMENTS_TRANSFERS_SCHET_INPUT-IN": "Выберите счет",
  "PAYMENTS_TRANSFERS_SCHET_LABEL-OUT": "Счет пополнения",
  "PAYMENTS_TRANSFERS_SCHET_INPUT-OUT": "Выберите счет",
  PAYMENTS_TRANSFERS_SUM: "Сумма перевода",
  PAYMENTS_TRANSFERS_CCY: "Валюта перевода",
  WRITE_OFF_CURRENCY: "Валюта списания",
  PAYMENTS_TRANSFERS_BTN: "Перевести",
  PAYMENTS_TRANSFERS_TO_OTHER_SCHET: "Счет",
  PAYMENTS_TRANSFERS_TO_OTHER_CARD: "Карта",
  PAYMENTS_TRANSFERS_TO_OTHER_PHONE: "Телефон",
  TELEPHONE: 'Телефон',
  "PAYMENTS_TRANSFERS_TO_OTHER_SCHET-NUMBER": "Счет получателя",
  "PAYMENTS_TRANSFERS_TO_OTHER_CARD-NUMBER": "Номер карты получателя",
  "PAYMENTS_TRANSFERS_TO_OTHER_CARD_DEBIT-NUMBER": "Номер карты списания",
  "PAYMENTS_TRANSFERS_TO_VISA_CARD-NUMBER": "Номер карты пополнения",
  "PAYMENTS_TRANSFERS_TO_OTHER_CARD-RECIPIENT_NAME": "Имя и фамилия получателя",
  "PAYMENTS_TRANSFERS_TO_OTHER_PHONE-NUMBER": "Телефон получателя",
  PAYMENTS_TRANSFERS_TO_OTHER_TEMPLATES: "Шаблоны переводов клиенту KICB",
  PAYMENTS_TRANSFERS_TO_OTHER: "Перевод на счет клиента KICB",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_TITLE: "Сомовые переводы в другие банки (клиринг и гросс)",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_SOURCE: "Счет списания",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_FAST_PAYMENT: "Срочный платеж/Гросс",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_DATE: "Дата перевода",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_NAME: "Наименование получателя",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_BIK: "БИК банка получателя",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_NAZNACHENIE: "Назначение",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_CODE: "Код платежа по классификатору",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_THEN: "Сумма перевода",
  PAYMENTS_TRANSFERS_TO_OTHER_BANK_TEMPLATES: "Шаблоны сомовых переводов в другие банки (клиринг/гросс)",
  PAYMENTS_TRANSFERS_SWIFT_TEMPLATES: "Шаблоны SWIFT переводов",
  PAYMENTS_TRANSFERS_SWIFT_TITLE: "Валютные переводы",
  PAYMENTS_TRANSFERS_SWIFT_VALUTA: "Валюта платежа",
  PAYMENTS_TRANSFERS_SWIFT_DATE: "Дата валютирования",
  PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER: "Банк-получатель",
  ELECTRIC_CAR: "Электрокар",
  BANK: "Банк",
  RELATION_WITH_BANK: "Отношение к Банку",
  PURPOSE_OF_OPENING: "Цель открытия электронного кошелька",
  MONTHLY_TURNOVER: "Ежемесячный оборот",
  SWIFT_TEXT_DETAILS: 'Настоящим подтверждаем, что информация, представленная в заявлении, является полной и достоверной.  Клиент ознакомлен и согласен с комиссией банка-корреспондента $50 в случае исправления/ дополнения инструкций/ запроса касательно перевода. Банк не несет ответственности за ошибки  или задержки при переводе вследствие небрежности или неполноты инструкций или пропусков, независящих от банка при заполнении данной формы.\n' + '\n' +
    'Банк будет выполнять поручения и инструкции в соответствии с требованиями  действующего законодательства Кыргызской Республики. \n' +
    ' А также подтверждаем, что, Банк проинформировал о возможных рисках  неисполнения, блокировки переводов, списания комиссии с основной суммы платежа  при отправке в РФ, со стороны Банков посредников, а также о возможном наложении новых санкций против банков РФ. Банк не несет ответственность за исполнение переводов в пользу Банков РФ в иностранной валюте.',
  "PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER-SWIFT": "SWIFT-код банка получателя",
  "PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER-FILIAL": "Филиал",
  "PAYMENTS_TRANSFERS_SWIFT_BANK_GETTER-REKVIZ": "Указать реквизиты Банка-посредника",
  LIMITS_PAYMENTS: "Платежи",
  LIMITS_TO_CLIENT: "Клиенту KICB",
  LIMITS_EXCHANGE_STANDART: "Обмен валют по стандартному курсу",
  LIMITS_EXCHANGE_SPECIAL: "Обмен валют по спец. курсу",
  LIMITS_MPC: "Перевод на карту другого Банка",
  LIMITS_GROSS: "В другой банк по КР в сомах (Гросс)",
  LIMITS_GROSS_CLEARING: "В другой банк в сомах по КР",
  LIMITS_CLEARING: "В другой банк по КР в сомах (Клиринг)",
  LIMITS_OPEN: "Открытие вклада",
  LIMITS_ADD: "Пополнение вклада",
  LIMITS_SYSTEM_OF_FAST_OPENINGS: "Быстрые денежные переводы",
  LIMITS_SWIFT: "За рубеж – SWIFT",
  SELECT_ALL: 'Выбрать все',
  NO_NOTIFICATIONS: 'Нет уведомлений',
  CARD_BLOCKED: 'Заблокирована',
  SETTING_CHANGE_PASSWORD: "Изменить пароль",
  SETTING_CHANGE_LOGIN: "Изменить логин",
  CHANGE_BUTTON: "Изменить",
  COMMISSION: 'Комиссия',
  ADDRESS: 'Адрес',
  SFKP: '№ СФКР',
  REASON_FOR_REISSUE: "Причина перевыпуска",
  LOSS_THEFT_DAMAGE_OTHER: "Утеря, кража или поломка",
  EXPIRATION_CARD: 'Истечение срока карты',
  MAINPAGE_TRANSACTIONS_CONFIRMATION: "Транзакции на подтверждении",
  VALUE_DATE: 'Дата валютирования',
  DOCUMENT_NO: 'No. документа',
  // Витрина - Открытие вклада

  TERMS_OF_AGREEMENT_TITLE: "Условия соглашения",
  CLEARING: 'Клиринг',
  GROSS: 'Гросс',
  INTERNAL_TRANSFER: 'Внутренние переводы',
  CHOOSE_DATE: 'Выберите дату',
  FOR_AMOUNT_INCLUDE: ({named}) => `для сумм ${named('from') !== '0' ? 'свыше ' + named('from') + ' \u{E001}' : ''}  до ${named('to')} \u{E001} (включительно)`,
  NO_TRANSACTION_HISTORY: 'Нет истории транзакций',
  RANGE: 'Диапазон',
  CHOOSE_CCY: 'Выберите валюту',
  DOCUMENT_NUMBER: '№ Документа',
  TIME_SENDING_TO_BANK: 'Время отправки в банк',
  INTERMEDIARY_BANK: 'Банк посредник',
  PAYMENTS_AMOUNT: 'Сумма платежа',
  FROM: 'От',
  TO: 'До',
  ATTENTION: 'Внимание!',
  ENTRANCE: 'В целях повышения безопасности системы существует ограничение по времени сеанса соединения с сервером системы. В случае отсутствия активности в течение 10  минут после авторизации система автоматически завершит' +
    ' сеанс соединения. Для возобновления работы Вам необходимо заново пройти авторизацию.',
  RECOVER_PASSWORD: 'Для восстановления забытого пароля Вам нужно ввести:\n<br>' +
    '-логин\n<br>' +
    '-номер телефона\n<br>' +
    '-ответить на контрольный вопрос\n<br>' +
    '-выбрать метод получения секретного кода',
  TRANSLATION_COSTS: 'Расходы по переводу',
  RECIPIENT_BANK_NAME: 'Наименование банка получателя',
  INTERMEDIARY_BANK_NAME: 'Наименование банка посредника',
  INTERMEDIARY_BANK_SWIFT_CODE: 'SWIFT-код банка посредника',
  RECIPIENT_BANK_SWIFT_CODE: 'SWIFT код банка получателя',
  RECIPIENT_BANK_SWIFT: 'SWIFT Банка получателя',
  RECIPIENT_BANK_ADDRESS: 'Адрес банка получателя',
  SWIFT_RECIPIENT_ACC_NO: 'Счет/IBAN получателя',
  RECIPIENT_ADDRESS: 'Адрес получателя',
  PAYMENT_PURPOSE: 'Назначение',
  TOTAL_DAILY: "Дневной лимит",
  TOTAL_MONTHLY: "Месячный лимит",
  TOTAL_MIN: "Мин. сумма на 1 операцию",
  TOTAL_MAX: "Макс сумма на 1 операцию ",
  VALUE_ABSOLUTE: "Фиксированная комиссия",
  VALUE_PRECENT: "Процентная комиссия",
  COMMISSION_MAX: "Максимум",
  COMMISSION_MIN: "Минимум",
  FIX_AMOUNT_PERCENT: "Дополнительная комиссия",
  TARIFFS_CCY: "Валюта тарифа",
  APP_VERSION: "Версия приложения",
  OFFER: "Оферта",
  PRIVACY_POLICY: 'Политика конфиденциальности',
  GO_TO_BANK_SITE: "Перейти на сайт банка",
  BANK_LICENSE: "Лицензия банка",
  USER_GUIDE: "Руководство пользователя",
  CHECKBOOK_ORDER: "Заказ чековой книжки",
  CHECKBOOK_QUANTITY_SHEETS: "состоит из 25 листов",
  CHECKBOOK_COMMISSION: "Комиссия за 1 чековую книжку",
  CHECKBOOK_TRANSFER_METHOD: "Способ передачи чековой книжки",
  CHECKBOOK_TRUST_TITLE: "Чековую книжку доверяем получить сотруднику\n",
  CHECKBOOK_TRUST_NAME: "Ф.И.О. доверенного сотрудника",
  CHECKBOOK_TRUST_PASSPORT_WHO: "Кем выдан",
  CHECKBOOK_TRUST_PASSPORT_WHEN: "Когда выдан",
  BANK_BRANCH: "Отделение банка",
  CHOOSE_BANK_BRANCH: "Выберите отделение банка",
  BY_MAIL: "По почте",
  BY_COURIER: "Курьером",
  COMMISSION_WRITE_OFF_ACCOUNT: "Комиссия за справку",
  CONTACT_PHONE_NUMBER: "Контактный номер телефона",
  ACCEPT_TERMS: "Принимаю условия Соглашения",
  TOTAL_COST: "Итоговая стоимость",
  SETTING_PIN_CODE: "Установить PIN код",
  RESERV_SAFEBOX: "Бронь сейфовой ячейки\n",
  RESERV_SAFEBOX_SIZE: "Размер сейфовой ячейки",
  RESERV_SAFEBOX_TERM: "Срок аренды",
  RESERV_SAFEBOX_AMOUNT: "Стоимость аренды\n",
  BOND_PURCHASE: "Приобретение облигаций\n",
  BOND_ISSUE_NUMBER: "Номер выпуска облигаций",
  BOND_NOMINAL_AMOUNT: "Номинальная стоимость",
  BOND_DATES_PAYMENTS: "Даты выплаты процентов",
  BOND_EFFECTIVE_RATE: "Эффективная ставка",
  BOND_MATURITY: "Срок обращения облигаций\n",
  BOND_SALE_PERIOD: "Период продажи облигаций\n",
  BOND_PURCHASE_QUANTITY: "Количество приобретаемых облигаций",
  DEPOSIT_TERM: "Срок вклада",
  DEPOSIT_RATE: "Процентная ставка",
  DEPOSIT_REPLENISHMENT: 'Совершенные операции в "KICB" не подлежат отмене, в связи, с чем просим Вас быть внимательными при отправлении транзакций; Разрешается пополнять только накопительный и детский тип депозитов; Пополнение осуществляется при наличии средств на расчетном/карточном счете держателя в валюте открытого депозита; С лимитами по пополнению депозитов можно ознакомиться в разделе \"Лимиты\"',
  DEPOSIT_TERMINATE_INFO: "При расторжении начисленные ранее проценты будут аннулированы согласно условиям договора",
  DEPOSIT_TERMINATE_SUCCESS_INFO: "Ваша заявка будет обработана в течение 2 банковских дней.",
  DISCHARGE_NO_TRANSACTION: "За данный период у Вас не было транзакций",
  DISCHARGE_TWODAYS: "За последние 2 дня",
  DISCHARGE_WEEK: "За последнюю неделю",
  DISCHARGE_MONTHLY: "За последний месяц",
  LIMITS_CURRENT: "Текущий",
  LIMITS_STANDARD: "Стандарт",
  LIMITS_INCREASED: "Увеличенный",
  LIMITS_ANOTHER: "Другой",
  LOAN_REFERENCE: 'Справка по кредиту',
  CONFIRMATION_OF_APPLICATION: 'Подтверждение заявки',
  FINAL_STATUS_OPERATION: "Окончательный статус операций необходимо просмотреть в Истории",
  TERM_PREPRAING_CHECKBOOK: 'Срок подготовки чековой книжки 1 рабочий день. Ответственный специалист свяжется с Вами',
  ACCOUNT_STATUS_BLOCKED: 'Заблокирован',
  CARD_EXPIRATION: 'Окончание срока действия карты',
  END_DEPOSIT: 'Окончание депозита',
  UPDATE_PASSPORT_DATE: 'Обновите паспорт',
  VALIDITY_PERIOD_PASSPORT: 'Срок действия паспорта до',
  PASSPORT_EXPIRATION_DATE: 'После истечения срока паспорта пользователь будет переведен в режим просмотра.',
  WILL_BE_BLOCKED: 'будет заблокирована',
  HOME: 'Главная',
  ARCHIVE_IS_EMPTY: 'Архив пуст',
  SET_MAIN_ACCOUNT_BY_DEFAULT: 'Текущий счет установлен по дефолту',
  SET_MAIN_ACCOUNT_BY_NOT_DEFAULT: 'Текущий счет больше не является дефолтным',
  SET_ACCOUNT_NAME_SUCCESS: 'Счет переименован',
  PAYMENT_CAUSE: 'Причина',
  AMOUNT_DEBIT: 'Сумма перевода',
  USER_PROFILE: 'Профиль пользователя',
  CARD_ACCOUNT: 'Карточный счет',
  OPERATIONS_MANAGEMENT_OF_KICB: 'Операционное Управление ЗАО «KICB»<br>Кыргызская республика, г. Бишкек, бульвар Эркиндик 21',
  FINAL_PIN_CODE: 'Для окончательной установки PIN-кода,<br>'
    + 'Вам необходимо пройти в банкомат и совершить любое действие с картой.<br>'
    + 'В целях безопасности, не сообщайте код посторонним',
  ENTER_CHANGE_LIMIT: 'Введите лимит на изменение',
  MAXIMUM_AMOUNT: 'Максимальная сумма',
  NUMBER_OF_OPERATIONS: 'Количество операций',
  CHECKOUT_OPERATION: 'Операция на кассе',
  ONLINE_SHOPPING: 'Интернет-покупки',
  POS_TERMINALS: 'POS терминалы',
  CARD_REPLENISMENT: 'Пополнение карты',
  SET_ONLINE_PAYMENTS_ON: 'Интернет платежи подключены успешно',
  SET_ONLINE_PAYMENTS_OFF: 'Интернет платежи отключены успешно',
  CARD_WILL_BE_BLOCKED: 'Карта будет заблокирована в течении 5-15 мин',
  CARD_WILL_BE_UNBLOCKED: 'Карта будет разблокирована в течении 5–15 мин.',
  SMS_NOTIFICATIONS_ON: 'СМС уведомления подключены успешно',
  SMS_NOTIFICATIONS_OFF: 'СМС уведомления отключены успешно',
  SELECT_DEPOSIT_TYPE: 'Выберите тип вклада',
  SELECT_DEPOSIT_TERM: 'Выберите срок вклада',
  DATE_OF_BIRTH: 'Дата рождения',
  DATE_OF_BIRTH_CHILD: "Дата рождения ребенка",
  BIRTH_CERTIFICATE: "Свидетельство о рождении",
  CHILD_DATA: "Данные ребенка",
  SEND_FOR_CONFIRMATION: 'Отправить на подтверждение',
  ABOUT_TRANSFER: 'О переводе',
  EXECUTOR: 'Исполнитель',
  STATUS_SIGNATURE_1: 'Статус подписи 1',
  STATUS_SIGNATURE_2: 'Статус подписи 2',
  RECIPIENT: 'Получатель',
  RECIPIENT_BANK: 'Банк получатель',
  PURPOSE_OF_PAYMENT: 'Назначение платежа',
  ACCOUNT_NUMBER_IBAN: 'Номер счета / IBAN',
  CORRESPONDENT_BANK: 'Банк корреспондент',
  COMMISSION_TYPE: 'Тип комиссии',
  COMMISSION_WITHHOLD: 'Комиссию за перевод удержать',
  TOTAL_FOR_CHARGE: "Итого к списанию",
  TRANSLATION_COSTS_REFERENCE: "“OUR” за счет отправителя; </br> “BEN”–за счет получателя Поле (только для USD).",
  IBAN_OR_ACCOUNT: 'IBAN / Счет',
  DETAIL_TRANSFER: "Детали перевода",
  INTERMEDIARY_BANK_SWIFT: "SWIFT банка посредника",
  KPP: "КПП",
  BIN: "БИН",
  KBE: "КБЕ",
  KNP: 'КНП',
  CORRESPONDENT_ACCOUNT: 'Корреспондентский счет',
  NAME_BANK: 'Наименование банка',
  ADDRESS_BANK: 'Адрес банка',
  SWIFT_OR_BIK: 'SWIFT / БИК',
  SEARCH_BY: 'Поиск по:',
  SEARCH_CORP_HISTORY: 'Поиск',
  NO_MATCHES: 'Нет совпадений',
  EXECUTION_DATE: 'Дата исполнения',
  ORDER_DEBIT_CARD: 'Оформить дебетовую карту',
  SELECT_CARD_TYPE: 'Выберите тип карты',
  NAME_AND_SURNAME_LAT: 'Имя и фамилия держателя карты на латинице',
  NAME_AND_SURNAME: 'Имя и фамилия',
  CODE_WORD: 'Кодовое слово',
  APPLICATION_INFO: 'Информация по заявке',
  CURRENCY_CARD: 'Валюта карты',
  CARD_OWNER: 'Держатель карты',
  DELIVERY_TYPE: 'Тип доставки',
  INFO_ACCOUNTS_AND_BALANCES: 'Справка по счетам и остаткам',
  HELP_LANGUAGE: 'Язык справки',
  RUSSIAN: 'Русский',
  ENGLISH: 'Английский',
  COMMISSION_FOR_HELP: 'Комиссия за справку',
  TYPE_HOW_GET_HELP: 'Способ получения справки',
  HELP_SUCCESS_INFO: 'Срок подготовки справки 1 рабочий день',
  APPLICATION_ACCEPTED: 'Ваша заявка принята в работу',
  BANK_WILL_CONTACT_SHORTLY: 'В ближайшее время с вами свяжется сотрудник банка',
  MESSAGE: 'Сообщение',
  QUESTION_CHANGED_SUCCESS: 'Контрольный вопрос успешно сменен',
  LOGIN_CHANGED_SUCCESS: 'Логин успешно сменен',
  ENTER_NAME_PAYMENT: 'Введите название платежа',
  PAYMENT_ACCOUNT: 'Расчетный счет',
  CREATE_TEMPLATE: 'Создание шаблона',
  NAME_TEMPLATE: 'Имя шаблона',
  WANT_TO_DELETE_PAYMENT_SCHEDULE: 'Вы действительно хотите удалить платеж по расписанию?',
  WANT_TO_DELETE_TEMPLATE: 'Вы действительно хотите удалить шаблон?',
  NAME_TEMPLATE_CHANGED_SUCCESS: 'Ваш шаблон переименован',
  TEMPLATE_DELETE_SUCCESS: 'Ваш шаблон удален',
  PAYMENT_SCHEDULE_DELETED_SUCCESS: 'Ваш платеж по расписанию удален',
  TEMPLATE_SAVED_SUCCESS: 'Шаблон сохранен',
  CREATE_PAYMENT_SCHEDULE: 'Создание платежа по расписанию',
  EDITING_PAYMENT_SCHEDULE: 'Редактирование платежа по расписанию',
  SCHEDULE_SAVED_SUCCESS: 'Платеж по расписанию сохранен',
  SCHEDULE_CHANGED_SUCCESS: 'Ваш платеж по расписанию изменен',
  SELECT_DATES_PAYMENTS_UP_TO_10: 'Выберите конкретные даты для осуществления платежей. Вы можете выбрать до 10 дат.',
  NO_REPETITIONS: 'Без повторений',
  MONDAY: 'Понедельник',
  TUESDAY: 'Вторник',
  WEDNESDAY: 'Среда',
  THURSDAY: 'Четверг',
  FRIDAY: 'Пятница',
  SATURDAY: 'Суббота',
  SUNDAY: 'Воскресенье',
  SELECT_DAY: 'Выберите день',
  PAYER_BENEFICIARY: 'Плательщик/Получатель',
  REQUISITES_BANK_KGS: `ЗАО «Кыргызский Инвестиционно-Кредитный Банк, Бишкек Кыргызская Республика<br> БИК`,
  REQUISITES_BANK_RUB: 'ЗАО Кыргызский Инвестиционно-Кредитный Банк <br> SWIFT: KICB KG 22 <br> г. Бишкек, Кыргызстан',
  REQUISITES_BANK_KZT: 'ЗАО Кыргызский Инвестиционно-Кредитный Банк <br> SWIFT: KICB KG 22 <br> г. Бишкек, Кыргызстан',
  REQUISITES_BANK_ANY: 'CJSC Kyrgyz Investment and Credit Bank <br> SWIFT: KICB KG 22 <br> Bishkek, Kyrgyz Republic',
  PIN_CODE_NOT_MATCH: 'PIN код не совпадает. Попробуйте еще раз',
  SEND_ANOTHER_TRANSFER: 'Отправить ещё перевод',
  DATE_CANNOT_BE_LATER: 'Дата не может превышать 5 дней от текущей даты.',
  SELECT_RENTAL_PERIOD: 'Выберите срок аренды',
  THANK_YOU_REQUEST_ACCEPTED: 'Ответственный специалист свяжется с Вами',
  DEPOSIT_AMOUNT: 'Сумма вклада',
  CHILD_NAME: "Имя ребенка",
  TITLE_IPC: "Переводы на карты Элкарт",
  TITLE_KITEP: 'Жаны Китеп',
  TITLE_DEAL: 'Обмен валют. Сделка',
  TITLE_WALLET: 'Пополнение кошелька Элсом',
  TITLE_CARD_OPENING: 'Получение дебетовой карты',
  TITLE_CARD_REOPENING: 'Перевыпуск карты',
  DEFAULT_HISTORY_TITLE: 'Неизвестный перевод',
  SERVICE: 'Принят к обработке',
  IN_PROCESS: 'Принят к обработке',
  CONFIRMED: 'Подтвержден',
  WAITING: 'Ожидает',
  STATUS_DICLINE: 'Отклонён',
  APPLICATION_ACCEPTED_FOR_PROCESSING: 'Спасибо! Заявление принято к обработке',
  FAILURE: 'Не принят',
  SUCCESS: 'Принят',
  DELETED: 'Отменен',
  ON_CONFIRMATION: 'На подтверждении',
  DECLINED: 'Отклонено',
  PERSONAL_ACCOUNT: "Лицевой счет",
  DATE_START: "Дата создания",
  TRANSFER_CLEARING_GROSS: "Тип перевода",
  ACCOUNT_DEBIT_NO: 'Счет списания',
  ACCOUNT_CREDIT_NO: 'Счет зачисления',
  periodicity: 'Периодичность',
  CLOSE: 'Закрыть',
  SELECTED_DATES: 'Назначенные даты',
  NUMBER_OF_MONTH: 'Число месяца',
  SENDER_NAME: 'Наименование отправителя',
  AMOUNT_CREDIT: 'Сумма к зачислению',
  CODE_KNP: 'Код платежа',
  TRANSFER_PURPOSE_TEXT: 'Назначения',
  CONTRACT_REF_NO: 'Номер контракта',
  district: 'Район или город',
  VO_CODE: 'Код VO',
  SCHOOL_CODE: 'Код школы',
  FULL_NAME_STUDENT: 'ФИО ученика',
  ACADEMIC_YEAR: 'Учебный год',
  CLASS: 'Класс',
  VEHICLE_NUMBER: 'Госномер',
  PAYMENT_CODE: 'Код оплаты',
  DEPOSIT_MAIN_INT_TYPE: 'Выплата процентов',
  EVENTS: 'События',
  LIMIT_CHANGED_1_HOUR: 'Лимит будет изменен в течение 1 часа',
  LOANS_TO_DATE: ({named}) => `до ${named('date')}`,
  INFO_TAX: 'Для уплаты налога Вам необходимо указать:' +
    '<br />–ИНН' +
    '<br />–место нахождения/регистрации объекта имущества или ведения экономической деятельности (область, район, если есть айыльный аймак);' +
    '<br />–государственный номер транспортного средства при уплате налога на транспорт;' +
    '<br />–сумму налога, подлежащую уплате.' +
    "Если Вы неверно указали вид налога или один из выше указанных реквизитов, ЗАО «КИКБ» не несет ответственности. Вам необходимо обратиться в налоговый орган. В случае переплаты излишек уплаченной суммы налога остается на лицевом счете налогоплательщика. Также ЗАО «КИКБ» настоятельно рекомендует Вам после уплаты налога снять копию чека об уплате в целях обеспечения его сохранности. Для своевременного зачисления денежных средств на Ваш лицевой счет уплачивайте налог заблаговременно Проверить факт произведенной уплаты налога Вы можете посредством электронного сервиса, предоставляемого на сайте ГНС при ПКР <a href='#' class='local-link local-link--dark local-link--underline'>(www.sti.gov.kg).</a>",
  OPENING_DEBET_CARD: 'Открытие дебетовой карты',
  CARD_PRODUCTION_TIME: 'Вы получите уведомление. Срок изготовления карты 5-7 рабочих дней.',
  LICENSE: 'Все права защищены. Лицензия НБКР №046',
  SEND: 'Отправить',
  SMS_NOTIFICATION: 'Внимание! При подключении данной услуги будет списываться комиссия согласно тарифам Банка.',
  REPAYMENT_SCHEDULE_LOAN: 'В случае реструктуризации кредита с отсрочкой погашения процентов, необходимо получить в Банке новый «График погашения» кредита.',
  TRANSFER_CONFIRMATION: 'Подтверждение перевода',
  TRANSACTIONS_SUCCESS_CONFIRMED: 'Транзакции успешно подтверждены',
  REJECT: 'Отклонить',
  NOT_VERIFIED: 'Не проверено',
  PAYMENTS_PROVIDERS: 'Платежи поставщикам услуг',
  PAYMENTS_SALARY_IMPORT: 'Импорт - документов',
  LOAN_ACCOUNT: 'Счет кредита',
  STATEMENT_TYPE: 'Тип справки',
  SELECT_LOAN: 'Выбрать кредит',
  NUMBER_OF_CHECKBOOKS: 'Количество чековых книжек',
  RECIPIENT_FIO: 'ФИО получателя',
  SENDER_FIO: 'ФИО отправителя',
  TRANSACTION_DETAILS: 'Детали перевода',
  CAR_LICENSE_PLAT: "Госномер автомобиля",
  REGION_OR_CITY: "Область или город",
  DISTRICT_OR_CITY: 'Район или город',
  STREET: 'Улица',
  MAILBOX: 'Почтовый ящик',
  REGISTERED_ADDRESS: 'Адрес по прописке',
  ACTUAL_ADDRESS: 'Адрес фактический',
  SELECT_REGION_OR_CITY: "Выберите область или город",
  CALCULATE_TAX: "Рассчитать налог",
  VEHICLE_TYPE: "Тип транспортного средства",
  SELECT_VEHICLE_TYPE: "Выберите тип транспорта",
  ENGINE_CAPACITY: "Объем двигателя, см3",
  YEAR_OF_EDITION: "Год выпуска",
  SELECT_YEAR_OF_EDITION: "Выберите год выпуска",
  SELECT_YEAR: "Выберите год",
  SELECT_COEFFICIENT: "Выберите коэффициент",
  SELECT_BASIC_TAX_VALUE: "Выберите базовую налоговую стоимость",
  CERTIFICAT_FEE: "Комиссия за справку",
  DELIVERY_FEE: "Комиссия за доставку",
  HOW_TO_RECEIVE: "Способ получения",
  COURIER: "Курьер",
  DATA_TRUST_USER: "Данные доверенного сотрудника",
  SELECTED_ACCOUNTS: "Выбранные счета",
  REGISTRATION_ELSOM: 'Регистрация ЭЛСОМ',
  LINK_ELSOM: 'Привязать ЭЛСОМ',
  SEND_SMS_FOR_CONFIRMATION: 'Отправить СМС для подтверждения',
  BREAK_AFTER_MINUTES: ({named}) => `Перерыв через ${named('minutes')} минут`,
  TO_LEARN_MORE: 'Узнать больше',
  SELECT_AIMAK: 'Выберите аймак',
  CURRENCY_TRANSACTION_CODE_VO_REFERENCE: "Код VO — 5-значный код валютной операции, который указывается при операциях между резидентом и нерезидентом России. Код определяет тип (цель) перевода.",
  KPP_REFERENCE: "КПП—это код, состоящий из 9 цифр, в которых зашифрована информация о постановке организации на учет в Налоговой службе РФ.",
  BIN_REFERENCE: "БИН—уникальный номер, формируемый для юр.лица и ИП, осуществляющего деятельность в виде совместного предпринимательства на территории Республики Казахстан.",
  KBE_REFERENCE: "Код Бенефициара - состоит из двух цифр: первая цифра указывает, является ли получатель резидентом Республики Казахстан, вторая –указывает сектор экономики, к которому он относится.",
  KNP_REFERENCE: "КНП - Код назначения платежа - трехзначное цифровое кодовое обозначение назначения платежа.",
  ATTENTION_SCHEDULED_PAYMENTS: 'Внимание! Платежи в те месяцы, в которых отсутствует данное число, будут производиться в последний день месяца.',
  FIELD_START_128: 'поле должно начинаться с "128"',
  FIELD_NEED_16_SYMBOLS: 'Поле должно содержать 16 символов.',
  BENEFICIARY_BANK: 'Банк получателя',
  NAME_OF_PAYMENT_BY_CLASSIFIER: 'Наименование платежа по классификатору',
  PAYMENT_TYPE: 'Вид платежа',
  FEE_AND_SALES_TAX: 'Комиссия и  НсП',
  RECIPIENT_ACCOUNT_NUMBER: 'Номер счета получателя',
  REQUISITES_RECIPIENT: "Реквизиты получателя",
  SELECT_LOAN_CCY: 'Выберите валюту кредита',
  PURPOSE_OF_TAKE_LOAN: 'Цель получения кредита',
  SELECT_PURPOSE_OF_TAKE_LOAN: 'Выберите цель получения кредита',
  DETAILS_FOR_PURPOSE_LOAN: 'Уточнения к цели получения кредита',
  MONTH_SHORT: 'мес.',
  YEAR_SHORT: 'г.',
  FREQUENCY_OF_INTERES_PAYMENT: 'ПЕРИОДИЧНОСТЬ ВЫПЛАТЫ ПРОЦЕНТОВ',
  MONTHLY: 'Ежемесячно',
  AT_END_OF_TERM: 'В конце срока',
  ENDING_SESSION: 'Завершение сессии',
  ENDING_SESSION_DETAILS: ({named}) => `Пользовательская сессия будет автоматически прекращена через ${named('sec')} секунд`,
  LOGIN_VIA_QR: 'Быстрый вход по QR-коду',
  TIMER_UPDATE_QR_CODE: ({named}) => `Повторить запрос QR-кода через ${named('sec')} секунд`,
  UPDATE_QR_CODE: 'Получить новый QR код',
  LOGOUT_SESSION: 'Выйти из сессии',
  CONTINUE_WORK: 'Продолжить работу',
  ACCEPT_TERMS_TRANSFER_MONEY: ({named}) => `Принимаю условия публичной оферты размещенной на сайте  <a target="_blank" href="${named('href')}" class="money-stream-form__agreement-link">Соглашения</a>`,
  ACCEPT_TERMS_ELSOM: ({named}) => `Принимаю условия публичной оферты размещенной на сайте  <a target="_blank" href="${named('href')}" class="money-stream-form__agreement-link">www.elsom.kg</a>`,
  MONEY_TRANSFER_RECEIVE_INFO: 'Перевод можно получить только в любом отделении KICB',
  MONEY_TRANSFER_ACCEPTED_FOR_PROCESSING: 'Принят к обработке',
  COMMISSION_CHECKBOOK_FEE: 'Комиссия за чековые книжки',
  ORDER_CARD_FEE: 'Комиссия за годовое обслуживание',
  ORDER_CARD_REOPENING_FEE: 'Комиссия за перевыпуск',
  CONFIRM: 'Подтвердить',
  SELECT_TRANSFER_CURRENCY: 'Выберите валюту перевода',
  SELECT_COUNTRY: 'Выберите страну ',
  SELECT_CITY: 'Выберите город',
  SELECT_ACCOUNT_COMMISSION: 'Счет списания комиссии',
  WITHHOLD_FREE_FROM_ACCOUNT: 'Комиссию удержать со счета',
  PAYMENT: 'Платеж',
  ATTACH_DOCUMENTS: 'Прикрепить документы',
  EARLY_COMPLETE_TEXT: 'Ваша заявка принята Банком в обработку. В ближайшее время с вами свяжется сотрудник банка.',
  CARD_BLOCKED_NO_TRANS_180: ({named}) => `Ваш счет ${named('acc')} будет заблокирован в связи с отсутствием движений по нему в течение 180 дней.`,
  ACCOUNT_BLOCKED: 'Блокировка счёта',
  PRIVATE_TRANSFER: 'Частный перевод',
  SELECT_DISTRICT_OR_CITY: 'Выберите район или город',
  NO_CURRENCY_RATES: 'Не найдены курсы валют для данной пары',
  SELECT_LOAN_TERM: 'Выберите срок кредита',
  ELSOM_INFO_INN: 'Для регистрации или привязки кошелька, необходим верный номер ИНН указанный в Банке',
  GET_CODE: 'Получить код',
  CATEGORY: 'Категория',
  CATEGORIES: 'Категории',
  REPLENISHMENT_ACCOUNT: 'Пополнение счета',
  INFORMATION_AGREEMENT: 'Настоящим подтверждаю достоверность данных указанных выше и даю согласие на регистрацию',
  SUCCESSFULLY_REGISTRED: 'Вы успешно зарегистрированы в системе ЭЛСОМ. Скачайте приложение ЭЛСОМ и введите полученный одноразовый код для активации кошелька',
  SET_FOR_CONFIRMATION: 'Отправлен на подтверждение',
  ENTER_YOUR_PHONE: 'Введите свой номер телефона',
  TRANSACTION_SUCCESSFULLY_REJECTED: 'Транзакции успешно отклонены',
  TRANSACTIONS_SUCCESSFULLY_CONFIRMED: 'Транзакции успешно подтверждены',
  LINK_APPLICATION: 'Скачайте мобильное приложение  для iOS и Android! Доступно для скачивания в AppStore и PlayMarket.',
  OUT: 'Отмена',
  SWIFT_TRANSFER: 'SWIFT переводы',
  CLEARING_GROSS_INTERNAL_TRANSFER: 'Клиринг/ Гросс/ Внутренние переводы',
  UPLOADING_DOCUMENT: 'Нажмите на "+" для загрузки документов',
  DOWNLAND_LIST: 'Загрузить список',
  DOWNLOADING_BATCH_TRANSFER: 'Загрузка пакетных переводов',
  LIST_OF_TRANSLATIONS: 'Список переводов',
  DOCUMENT_NUMBER_PLACEHOLDER: 'Документ номер',
  SEND_TRANSACTIONS_TO_PRINT: 'отправить транзакции на печать',
  SEND_TRANSACTIONS_TO_THE_BANK: 'отправить транзакции в банк',
  SHOW_ALL_TRANSACTIONS: 'показать все транзакции',
  PRINT: 'печать',
  SEND_BANK: 'Отправить в банк',
  ALLOWED_TYPES_OF_OPERATIONS: 'Разрешенные типы операций',
  ACCOUNTS_TO_VIEW: 'Счета для просмотра',
  ACCOUNTS_FOR_TRANSACTIONS: 'Счета для операций',
  USER_RIGHT: 'Права пользователя',
  READING_MODE: 'Режим чтения',
  CREATING_OPERATIONS: 'Создание операций',
  COORDINATION_OF_OPERATION: 'Согласование операций',
  TOKEN: 'Токен',
  CONFIRMATION_THE_OPERATION: 'Подтверждение операции',
  SALARY_IMPORT: 'Зарплата - Импорт',
  CONFIRM_SELECTED: 'Подтвердить выбранные',
  REJECT_SELECTED: ' Отклонить выбранные',
  DOCUMENT_WITH_AN_ERROR: 'Документы с ошибкой',
  NUMBER_ATTACHED_FILES: 'Количество вложенных файлов',
  COMMISSION_FROM_ACCOUNT: 'Комиссия со счета',
  CLIENT_CODE: 'Код клиента',
  APPLICATION_HAS_BEEN: 'Ваша заявка принята Банком в работу. Срок подготовки справки 1 рабочий день.',
  APPLICATION_HAS_BEEN_CORP: 'Срок подготовки справки 1 рабочий день.',
  APPLICATION_CHECK_BOOK_CORP: 'Срок подготовки 1 рабочий день.',
  BUY_BONDS_CORP: 'Ваша заявка принята Банком в работу.',
  YOU_ARE_WELCOME: 'Вас приветствует служба поддержки KICB.',
  ACCEPTANCE_TIME: 'Время принятия: до',
  IAM_FAMILIAR_TERMS: 'Ознакомлен(а) с условиями перевода',
  LINK_PHONE_NUMBER_TO_VISA_ALIAS: 'Visa Direct',
  CONFIRMATION_CARD_BINDING: 'Подтверждение привязки карты к номеру мобильного телефона',
  CARD_BINDING_DESCRIPTION: 'Данный функционал свяжет Ваш номер мобильного телефона с выбранной картой Visa для получения переводов. Любая предыдущая привязка карты с мобильным телефоном будет прекращена',
  READY_SEND_VISA_ALIAS: 'Все готово для оплаты, отправки и получения средств с помощью карты KICB и Visa Direct.',
  YOUR_MOBILE_NUMBER: 'Ваш номер мобильного',
  YOUR_NAME_BE_DISPLAYED: 'Ваше имя будет отображаться как',
  SEND_FUNDS_VIA_MOBILE: 'когда, Вам будут отправлять средства через номер мобильного телефона.',
  LINKED_CARD: 'Привязанная карта',
  YOU_ACTIVATED_ONE_CARD: 'Вы активировали 1 карту KICB для Visa Direct',
  LINKED_MOBILE_PHONE_NUMBER: 'Привязанный номер мобильного телефона',
  NAME_ACCOUNT: 'Имя аккаунта',
  FOUND_SENT: 'Средства, отправленные на Ваш номер мобильного \n телефона, будут зачислены на привязанную карту',
  DONE: 'Готово',
  VISA_ALIAS_ATTENTION: ({named}) => `Ваш номер мобильного телефона уже привязан к Visa Direct по другой карте (${named('bankName')}). Желаете привязать к данной карте?`,
  GOLD_CROWN: 'Тарифы на систему денежных переводов “Золотая Корона“',
  COLD_CROWN_PAYMENT: 'С тарифами на денежные переводы “Золотая корона“ можете ознакомиться здесь',
  GOLDEN_CROWN_THREE: 'С пунктами выдачи денежного перевода можете ознакомиться здесь.',
  TOTAL_AMOUNT: "Общая сумма",
  NUMBER_OF_TRANSACTIONS: "Количество транзакций",
  CVC: "CVC",
  CARD_EXPIRATION_DATE: "ММ/ГГ",
  CARD_VISA_EXPIRATION_DATE: "ММ/ГГ",
  GENERATE_PAYMENT_CODE: "Для формирования кода оплаты нажмите сюда",
  SALYK_INFO: "Далее справочники Государственной Налоговой Службы будут только на русском языке",
  INDIVIDUAL_ENTREPRENEUR: "Индивидуальный предприниматель",
  MY_QR: "Мой QR",
  GENERATE_QR: "Сгенерировать QR для точки продаж",
  NAME_QR: "Наименование торговой точки",
  ENTER_DATA: "Введите данные",
  ADD: "Добавить",
  VIEW_QR: "Показать QR",
  QR_TURNOVERS: "Обороты по QR",
  ADMINISTRATION: "Управление",
  TITLE_QR: "Название",
  DO_YOU_REALLY_DELETE_QR: "Вы действительно хотите удалить QR?",
  IN_MY_QR: "В Мой QR",
  NOT_SPECIFIED: "Не указан",
  STATEMENT_FOR_LAST_24_HOURS: "Выписка за последние 24 часа",
  NO_STATEMENT: "Нет выписки",
  SELECT_FROM_LIST: "Выберите из списка",
  LINKED_QR: "Подвязан QR",
  INACTIVE: "Неактивный",
  CHECK_DATA_CHANGING: "Проверьте данные перед изменением",
  LINKED_USER: "Привязанные пользователи",
  SELECT_WILL_BE: "Выбранные вами пользователи будут переведены в статус",
  LINKED: "привязанные",
  DELETE_USER: "Удаленные пользователи",
  UNTETHERED: "отвязанные",
  QR_SUCCESSFULLY_DELETED: "QR успешно удален",
  CHOOSE_ACCOUNT: "Выберите счет",
  CONTINUE: "Продолжить",
  DONT_HAVE_ACTIVE_QR: "У вас нет активных QR",
  CHECK_DATA_BEFORE_ADDING: "Проверьте данные перед добавлением",
  SELECT_USER_WHO:  'Вы можете выбрать одного или нескольких пользователей, которым будет предоставлен доступ для просмотра входящих платежей по QR ' +
    '<br> Если в указанном списке Вы не обнаружили нужного Вам пользователя, то необходимо его зарегистрировать в отделении Банка',
  PAYMENT_ELQR: 'Оплата по QR',
  EDITING_USERS: "Редактирование пользователей",
  SELECT_USER_LINK: "Выберите пользователя(ей), чтобы привязать/отвязать от QR",
  EMPLOYEE_NOT_SELECTED: "Сотрудник не выбран",
  SAVE_FOR_PRINTING: "Сохранить для распечатки",
  RETURN_TO_QR_LIST: "Вернуться в список QR",
  SUCCESSFULLY: "Успешно",
  AMOUNT: "Сумма оборота по QR за 24 часа",
  MY_POS: "Мой POS",
  QR_TRANSLATION: "Перевод по QR",
  OPENING_AN_ACCOUNT: "Открытие нового счета",
  CURRENCY_RUSSIAN_RUBLE: "Российский рубль",
  CURRENCY_KAZAKH_TENGE: "Казахский тенге",
  CURRENCY_TURKISH_LIRAS: "Турецкие лиры",
  CURRENCY_CHINESE_YUAN: "Китайский юань",
  CURRENCY_EURO: "Евро",
  CURRENCY_POUND: "Английский фунт",
  CURRENCY_SWISS_FRANC: "Швейцарский франк",
  CURRENCY_USA_DOLLAR: "Доллар США",
  CURRENCY_KYRGYZSTAN_SOM: "Кыргыский сом",
  OPENING_ACCOUNT: "Открытие счёта",
  OPEN_ACC: "Открыть счет",
  CREATE_AN_INVOICE_WITH_QR: "Создать счет на оплату с QR",
  CREATING_INVOICE_WITH_QR: "Создание счета на оплату с QR",
  SELECT_ACCOUNT_FUNDS_SHOULD_RECEIVED: "Выберите счет, куда должны поступить средства",
  SELECT_TYPE_CREATE: "Выберите тип создания",
  MANUALLY: "Вручную",
  AUTOMATICALLY: "Автоматически",
  INVOICE: "Счет на оплату №",
  CLIENT_NAME: "Наименование заказчика",
  CLIENT_DETAILS: "Данные заказчика",
  NUMBER_ACCOUNT: "№ счета",
  TOTAL_AMOUNT_INVOICE: "Итоговая сумма",
  SELECT_FILE_UPLOAD_FORMAT: "Загрузите файл в одном из ниже перечисленных форматах. Для получения информации о формате, нажмите на кнопку  \"?\"",
  QUANTITY: "Количество",
  PRICE: "Цена",
  ADDED_MORE: "Добавить еще",
  FILE_PREVIEW: "Просмотр файлов для загрузки",
  NAME: "Наименование",
  YOU_DONT_HAVE_RIGHTS: "У вас нет прав доступа",
  UPLOAD_THE_FILE_OF_FOLLOWING: "Загрузите файл в одном из ниже перечисленных ",
  SELECT_ACCOUNT_FUNDS_SHOULD_RECEIVED2: "Выберите счет, куда должны поступать средства",
  ADDRESS_QR: "Адрес торговой точки",
  CREATING_INVOICE_WITH_QR_CODE: "Создание накладной с QR"
}


