# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protofile.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protofile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotofile.proto\x12\x07\x64mz_api\"#\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x8f\x01\n\x11LoginResponseData\x12\x12\n\nsessionKey\x18\x01 \x01(\t\x12\x11\n\tsessionId\x18\x02 \x01(\t\x12\x13\n\x0botpDelivery\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x1a\n\x12securityQuestionId\x18\x05 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x06 \x01(\t\"i\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12(\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1a.dmz_api.LoginResponseData\x12\x1d\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x0e.dmz_api.Error2M\n\nWebAuthApi\x12?\n\x0c\x61uthenticate\x12\x15.dmz_api.LoginRequest\x1a\x16.dmz_api.LoginResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERROR']._serialized_start=28
  _globals['_ERROR']._serialized_end=63
  _globals['_LOGINREQUEST']._serialized_start=65
  _globals['_LOGINREQUEST']._serialized_end=115
  _globals['_LOGINRESPONSEDATA']._serialized_start=118
  _globals['_LOGINRESPONSEDATA']._serialized_end=261
  _globals['_LOGINRESPONSE']._serialized_start=263
  _globals['_LOGINRESPONSE']._serialized_end=368
  _globals['_WEBAUTHAPI']._serialized_start=370
  _globals['_WEBAUTHAPI']._serialized_end=447
# @@protoc_insertion_point(module_scope)
