# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import astrasend_internal_api_pb2 as astrasend__internal__api__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in astrasend_internal_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AstrasendInternalApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.searchReceiveMoney = channel.unary_unary(
                '/astrasend_internal_api.AstrasendInternalApi/searchReceiveMoney',
                request_serializer=astrasend__internal__api__pb2.SearchReceiveMoneyRequest.SerializeToString,
                response_deserializer=astrasend__internal__api__pb2.SearchReceiveMoneyResponse.FromString,
                _registered_method=True)
        self.receiveMoneyPay = channel.unary_unary(
                '/astrasend_internal_api.AstrasendInternalApi/receiveMoneyPay',
                request_serializer=astrasend__internal__api__pb2.ReceiveMoneyPayRequest.SerializeToString,
                response_deserializer=astrasend__internal__api__pb2.ReceiveMoneyPayResponse.FromString,
                _registered_method=True)
        self.payStatus = channel.unary_unary(
                '/astrasend_internal_api.AstrasendInternalApi/payStatus',
                request_serializer=astrasend__internal__api__pb2.PayStatusRequest.SerializeToString,
                response_deserializer=astrasend__internal__api__pb2.PayStatusResponse.FromString,
                _registered_method=True)


class AstrasendInternalApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def searchReceiveMoney(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receiveMoneyPay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def payStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AstrasendInternalApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'searchReceiveMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.searchReceiveMoney,
                    request_deserializer=astrasend__internal__api__pb2.SearchReceiveMoneyRequest.FromString,
                    response_serializer=astrasend__internal__api__pb2.SearchReceiveMoneyResponse.SerializeToString,
            ),
            'receiveMoneyPay': grpc.unary_unary_rpc_method_handler(
                    servicer.receiveMoneyPay,
                    request_deserializer=astrasend__internal__api__pb2.ReceiveMoneyPayRequest.FromString,
                    response_serializer=astrasend__internal__api__pb2.ReceiveMoneyPayResponse.SerializeToString,
            ),
            'payStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.payStatus,
                    request_deserializer=astrasend__internal__api__pb2.PayStatusRequest.FromString,
                    response_serializer=astrasend__internal__api__pb2.PayStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astrasend_internal_api.AstrasendInternalApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astrasend_internal_api.AstrasendInternalApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AstrasendInternalApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def searchReceiveMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astrasend_internal_api.AstrasendInternalApi/searchReceiveMoney',
            astrasend__internal__api__pb2.SearchReceiveMoneyRequest.SerializeToString,
            astrasend__internal__api__pb2.SearchReceiveMoneyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def receiveMoneyPay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astrasend_internal_api.AstrasendInternalApi/receiveMoneyPay',
            astrasend__internal__api__pb2.ReceiveMoneyPayRequest.SerializeToString,
            astrasend__internal__api__pb2.ReceiveMoneyPayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def payStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astrasend_internal_api.AstrasendInternalApi/payStatus',
            astrasend__internal__api__pb2.PayStatusRequest.SerializeToString,
            astrasend__internal__api__pb2.PayStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
